### ISSUE TITLE
Blank page on chrome (mac & win): networkVersion undefined

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#102]
**Bug Description**
User reports seeing a blank page when accessing goodswap.xyz.

**Additional Context**

Devices tested by user
Mac OS 12.0.1 (21A559)
Chrome Version 96.0.4664.110 (Official Build) (arm64)  -- latest version 

and

Chrome 96 - on windows 10

**CONSOLE**
<img width="715" alt="Screen Shot 2021-12-22 at 19 34 22" src="https://user-images.githubusercontent.com/49105975/147133066-8e173183-c26b-4fcf-8d37-b9f7e27a975c.png">

**Comment by sepu85** [comment]
hi @patpedrosa can you check again taking into consideration metamask settings? 

errors are related to "Network Version" so this seems a problem to be related to user's wallet configuration.

**Comment by patpedrosa** [comment]
Raph doesn't not have metamask

**Comment by sepu85** [comment]
it won´t work then! the UI is only accesible through metamask. Please share this with user: https://www.notion.so/gooddollar/How-to-Connect-G-Address-to-Metamask-c67f0a0f482d4692b372476144011bbc 

then he can connect from the same browser.

**Comment by sirpy** [comment]
@sepu85 it should work without metamask. in this case there's already other issue for that
