### ISSUE TITLE
G$ Rewards - Value in USD does not correspond to G$ price.

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#107]
**Bug Description**
Rewards value doesn't correspond to real price!

<img width="822" alt="Captura de pantalla 2021-12-28 a las 13 31 16" src="https://user-images.githubusercontent.com/22507864/147566539-b128b96c-324f-47b8-b069-ec234c77fe95.png">

**Steps to Reproduce**
1. Stake into the GoodStake positions
2. Go to portfolio, after a certain time earning G$rewards, check that value in USD does not correspond to proper price
...

**Expected Behavior**
680132 G$s *0,00016 USD/G$ = 111.54 G$

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by mukulshakya** [comment]
Hey @sepu85 @sirpy i couldn't find test faucet for fuse. Can you help?

**Comment by mukulshakya** [comment]
This is what i can see RN 
![image](https://user-images.githubusercontent.com/34328275/148771558-3f1032c6-4145-4fcb-b57d-a378ec15cc9c.png)

**Comment by sepu85** [comment]
you are the dev @mukulshakya , not me, I can't say why you don´t see that option, but it should be there!

maybe @sirpy can tell you something

**Comment by sirpy** [comment]
@mukulshakya check your console log for errors
maybe the kovan rpc is exhausted use a custom one... register on infura or something

**Comment by patpedrosa** [comment]
<img width="1603" alt="Screen Shot 2022-01-17 at 18 10 34" src="https://user-images.githubusercontent.com/49105975/149837456-96830546-afea-44da-b5ee-feb16e41ea28.png">

Looks to me like a decimal issue. Ran that g$ value through the swap and it amounts to ~4.00 USD.

**Comment by sepu85** [comment]
@YpetrovAJ please prioritize solving this issue!

**Comment by YpetrovAJ** [comment]
I'll send the PR soon, dealing with it right now @sepu85

**Comment by patpedrosa** [comment]
Is this fix live on prod? I'm seeing this still:

<img width="1052" alt="Screen Shot 2022-01-26 at 09 53 18" src="https://user-images.githubusercontent.com/49105975/151166313-568e2bbc-0872-45fa-8c93-00b482219136.png">

**Comment by artqadev** [comment]
Hi there :) 
Looks like fixed:
![image](https://user-images.githubusercontent.com/98735241/151990238-caec1e71-2f7c-4d79-ad86-f3ea34c16849.png)

**Comment by sirpy** [comment]
yes, we will update prod
