### ISSUE TITLE
(Bug) swap details incorrect

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#108]
When swapping between cdai<->G$ meaning directly from reserve.
on Ethereum (production probably also on kovan)
- [x] price is incorrect
- [x] price impact is always 0
- [x] when switching the trade direction, the price always stays the same. it changes for a second but then switches back.
- [ ] ~~waiting for confirmation modal should show amount we swapping not price~~
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/e1754175-46ea-4d6c-a5cf-18d693e3f542)

**Comment by imanshu03** [comment]
@sirpy I have fixed the price issue. For Price Impact issue, our application does not computes the price impact for cDai and Dai while fetching meta information on selling i.e Swapping from G$ to cDai/Dai. Do you want me to add price impact for this case scenario ?

**Comment by sirpy** [comment]
@imanshu03 
yes. new price is 
P = (cR + (buy amount/-sellReturn)) / (cG + (buyReturn/sell amount))*rr
cR = current cdai in reserve
rr = current reserve ratio
cG = current G$ supply

price impact = % diff between new price and current price

**Comment by sirpy** [comment]
@imanshu03 hmm in second thought, how is the price impact calculated in other cases?

**Comment by sirpy** [comment]
i believe the price impact should actually be in all cases
when buying: buyReturn/cdaiAmount vs current G$ price at reserve in cDAI
when selling: 1/(sellReturn/g$Amount) vs current G$ price at reserve in cDAI

**Comment by imanshu03** [comment]
@sirpy I'll look how are we currently calculating the price impact for other swaps. Just some quick questions:
Do we need to show the new price to the user by formula you stated ?
Is current price the price that we are currently computing without the formula or anything else ?

**Comment by sirpy** [comment]
@imanshu03 
The new price is according to the first formula I gave p=R/G*rr
current price is received directly from the reserve. i believe there's a function for that "g$price". the reserve is actually using the above formula that I gave you.

**Comment by imanshu03** [comment]
@sirpy Okay, Can I use that function for computing new price ?

**Comment by sirpy** [comment]
@imanshu03 yeah ok i found another mistake, and I just now realized about your question of price.
And i'm not sure how to handle it.
price should be the actual price user will be getting per G$
price impact should be the expected spot price at the reserve after the swap vs current price at the reserve.

the price should be calculated as:
when buying: buyReturn/input token
when selling: 1/output token/g$

And the price impact should be calculated using the p=R/G*rr formula i gave you vs the current price at the reserve.

Now i'm not sure how to handle it, because we should probably show a warning to the user both when price impact is high and when actual price is significantly different then current price.
To find the difference between current price and actual price you would  have to convert everything to $ value or some other intermediary token like ETH.

when buying: buyReturn/input token dollar value vs current G$ price at reserve in **DAI ($)**
when selling: 1/output token dollar value/g$ vs current G$ price at reserve in **DAI ($)**

can you tell me what are the current formulas for calculating price and price impact?
g$price will always get you the current price from the reserve

**Comment by imanshu03** [comment]
![Screenshot 2021-12-30 at 4.21.22 PM.png](https://images.zenhubusercontent.com/61925bd4897d42d4514e110d/d6244c34-cc0e-46f5-9fef-ffaf4efeecae)![Screenshot 2021-12-30 at 4.21.36 PM.png](https://images.zenhubusercontent.com/61925bd4897d42d4514e110d/f15d2015-153c-41ea-b685-cce6a16e895c)

Currently this is how I have handled the Price. If you can take a look and tell me if its correct way or not

**Comment by imanshu03** [comment]
@sirpy currently we are calculating the price as follows :

buying - inputAmount / outputAmount(Fraction) * outputAmount(Decimal scale)
selling - outputAmount * inputAmount(Decimal Scale) / inputAmount(Fraction)

**Comment by sirpy** [comment]
The price impact doesnt look logical. cdai<->G$ should result in almost 0% price impact as this is exchanging at the reserve directly.
what is the price impact calculation for X->cdai->G$ ?

**Comment by sirpy** [comment]
@imanshu03 uniswap sdk has a helper method to calcualate price impact
see https://github.com/Uniswap/sdk-core/blob/main/src/utils/computePriceImpact.test.ts

so price impact is the difference between the current price vs the actual price

**Comment by imanshu03** [comment]
@sirpy It is same for both the scenarios i.e. price impact is difference between current price vs actual price for both buying/selling ?

**Comment by imanshu03** [comment]
@sirpy currently the price impact for buying is calculated as follow :-
priceImpact = 1 - minimumOutputAmount / cDaiAmount / G$ to cDai ratio * 10^6

**Comment by sirpy** [comment]
@imanshu03 
1. the price impact is calculated on the output token. so when selling it is relative to the output token
2. i'm not sure about the calculation, i gave you uniswap that should be the baseline to understanding how to calculate price impact. But for sure it would need to be adapted per token, the calculation you wrote uses cDaiAmount but that is only available when buying with cdai, when buying with some other token you would have to find out how much is it worth in cDai. ie if you buy with 1ETH how many cDAIs is that worth.

**Comment by imanshu03** [comment]
@sirpy cDai Amount that I mentioned is relative to the input token. If input token is something else other than cDai, we first convert our input token amount to cDai amount and then calculate the price impact

**Comment by sirpy** [comment]
@imanshu03 ok perfect

**Comment by imanshu03** [comment]
@sirpy Is the formula for price impact calculation for buying is correct or not ?

**Comment by sirpy** [comment]
1. i dont know if it is correct. i gave you the uniswap file with the formula.
2. what kind of difficulty, I cant help if you dont elaborate. please use slack to discuss this in realtime

**Comment by imanshu03** [comment]
@sirpy 
Price Impact for Buying is calculated as follows :- (G$ - cDai to G$) /  (cDai to G$)
G$ -> output Amount
cDai to G$ ->  Input token converted to cDai token and then cDai token converted to G$ using G$ to cDai ratio at reserve

Which is same as one done in uniswap sdk computePriceImpact method. Price Impact calculation is done correctly as expected, I'll look into selling price Impact calculation and update you

**Comment by sepu85** [comment]
hey, I have just discovered one more error retaled to this:

<img width="733" alt="Captura de pantalla 2022-01-10 a las 12 05 07" src="https://user-images.githubusercontent.com/22507864/148755961-8177fc0f-8653-4f74-a5a3-4c4aeeac80a3.png">

<img width="721" alt="Captura de pantalla 2022-01-10 a las 11 57 40" src="https://user-images.githubusercontent.com/22507864/148755784-2fedd0b5-a1d4-4c1f-8fce-c11747f76521.png">

when `Waiting for Confirmation` the disclosed data of amount of tokens being swapped is wrong as it shows the relative price among the swapped tokens, not the amount of tokens (ETH in this case) to be swapped.

@imanshu03 @sirpy should this be a separate issue or this thread is ok? if new issue is needed, can you please open it?

**Comment by sirpy** [comment]
@imanshu03 on mainnet (production) things doesnt seem to be working as expected
1. gdx is always "-"
2. price impact doesnt seem correct. in the image you see price is 5702 per dai and current price in reserve is around 0.17 for 1000 = 1000/0.173 = 5780
the price impact is 1 - 5702/5780 = 1.4%
3. G$ icon is missing
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/76bcd9ac-6019-449a-9ad7-22624c94abdc)

**Comment by sirpy** [comment]
@imanshu03 i've pushed a fix to master for gdx + price impact
please verify

**Comment by imanshu03** [comment]
@sirpy I believe the price impact is wrong for buying. Please refer the screenshot
![Screenshot 2022-01-12 at 10.40.38 AM.png](https://images.zenhubusercontent.com/61925bd4897d42d4514e110d/ccee2661-1881-4a7c-a95d-761e9ea0d7d0)

**Comment by sirpy** [comment]
@imanshu03 so just fix it dont assign it to me

**Comment by artqadev** [comment]
Hi everyone :)
This seems to be fixed:
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/a6cfc567-4d50-405e-b267-4c5f65264030)
But @sepu85 can you please tell me if it has already been fixed (something changed)? 'Cause it seems like not:
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/32cd4878-d9ad-488c-bb9b-4c6b2dd57c5b)
Correct me if I'm wrong, please.

Thank you!
