### ISSUE TITLE
User should be aware that he is swapping on FuseSwap

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#112]
When user is on mainnet (ethereum) he buys/sells directly on the gooddollar reserve which can mint as many gooddollars as the user wants to buy.
The reserve has very low slippage/volatility relative to AMMs (ie uniswap)
When user is on fuse he buys/sells on fuseswap which not only have a different price then the reserve but is also more volatile

- [ ] when swapping on fuse add fusefi logo at the top (where it says "SWAP")
- [ ] add some disclaimer/explanation text next to it
- [ ] create + add a GoodReserve logo when swapping on mainnet via reserve

**Comment by YpetrovAJ** [comment]
Could you please clarify what should we do there directly? or give us some steps? 

@sirpy

**Comment by sepu85** [comment]
@YpetrovAJ swapping from protocol UI connect to two different markets, with different dynamics and prices.

When connected to Ethereum, the UI interacts with the GoodReserve AMM (current price on nav bar is ok), so we'd like to add a GoodReserve logo (we don´t have it ready) there.

But when connected to Fuse, we interact with a third party market, FuseSwap market, it has a different price (so changing the price when connected to Fuse is a new requirement use this a a price source: https://info.fuseswap.com/token/0x495d133b938596c9984d462f007b676bdc57ecec

and we can also add FuseSwap logo already:
![image](https://user-images.githubusercontent.com/22507864/149333823-cec7a077-0700-4531-b53a-b3f41fd6b975.png)

**Comment by sepu85** [comment]
![image](https://user-images.githubusercontent.com/22507864/149334672-847c7539-878e-4407-b442-8cbbc974fa1f.png)

**Comment by YpetrovAJ** [comment]
Fuse swap - [here](https://www.figma.com/file/qQnLAqI49HHbvHr1o1xD1a/GoodDollar?node-id=41%3A2460)

Goodreserve swap - [here](https://www.figma.com/file/qQnLAqI49HHbvHr1o1xD1a/GoodDollar?node-id=56%3A1225)

@sepu85 @sirpy

**Comment by sepu85** [comment]
this is good! @YpetrovAJ 

please remember also that FuseSwap G$ price should be read from the right source!

**Comment by sirpy** [comment]
@sepu85 @YpetrovAJ 
the "Swap" prefix looks strange, lets either remove it or change to "Swap On"
regarding price, the url is irrelevant, it should be done via existing available code.

@sepu85 My thought is that we should display both prices all the time
ie
reserve: 0.17
fuseswap: 0.2

**Comment by sirpy** [comment]
@sepu85 to write explanation texts
@YpetrovAJ need from the designer a place for text.

**Comment by sirpy** [comment]
@YpetrovAJ @Devartjoker see texts in previous comment
also use new "voltage" logo instead of fuseswap. see app.fuse.fi

**Comment by sirpy** [comment]
@YpetrovAJ 
take the latest logo from app.fuse.fi

**Comment by sirpy** [comment]
@1ucius @L03TJ3 @YpetrovAJ the text info texts needs spelling corrections and to say voltage swap instead of fuseswap

**Comment by artqadev** [comment]
Prod checked
