### ISSUE TITLE
User should see amount being swapped in waiting for confirmation modal

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#121]
Modal shows price it should show the amounts
https://user-images.githubusercontent.com/22507864/148755784-2fedd0b5-a1d4-4c1f-8fce-c11747f76521.png

**Comment by sirpy** [comment]
@sepu85 can you clarify what is the exact data/message user should see?

**Comment by sepu85** [comment]
IDK, I think it's ok as it is. I mean, the amount being swapped is shown correctly (0.1 ETH and 1819292.38 G$) while showing below the price. 

In case we want to improve this UX, I suggest to do what SushiSwap does, add a double arrow button so user can see the price in both directions (G$ price in ETH OR WTH price in G$)
<img width="698" alt="Captura de pantalla 2022-01-18 a las 13 41 09" src="https://user-images.githubusercontent.com/22507864/149939236-de86dc47-0610-4f84-a738-1972496167c7.png">

<img width="713" alt="Captura de pantalla 2022-01-18 a las 16 35 50" src="https://user-images.githubusercontent.com/22507864/149968350-6f7539e7-c957-40c7-844c-03dce8d92875.png">

**Comment by sirpy** [comment]
@sepu85 i attached the wrong image
this is the correct one
https://user-images.githubusercontent.com/22507864/148755784-2fedd0b5-a1d4-4c1f-8fce-c11747f76521.png

**Comment by sepu85** [comment]
I'm lost @sirpy , could you clarify what do you need from me?

**Comment by sirpy** [comment]
@sepu85 this is regarding your comment in issue #108 
see here
https://app.zenhub.com/workspaces/protocol-ui-team-61559a6a33275e00141f8ee4/issues/gooddollar/goodprotocolui/108#issuecomment-1008766806

**Comment by sepu85** [comment]
got it! yeah, as you said, it currently shows price when it should show the amounts, so I propose the following message:

*Swapping `X amount` `[Origin token]` per `Y amount` `[Destination Token]`* 

see that *per* is in lowercase

**Comment by sirpy** [comment]
not implementing
