### ISSUE TITLE
[BUG] Cropped GA Dashboard embed

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#123]
**Bug Description**
When you click on the dashboard, it loads the Trust Fund page and it seems like the first load sets the viewport. As you navigate to a different page, the charts that cross the threshold set by Trust Fund are cropped and unreadable.

**Steps to Reproduce**
1. Go to Dashboard
2. See Trust Fund page
3. Navigate to Token
4. Fail to see beyond the title "Value in reserve"

**Expected Behaviour**
A user should be able to read all graphs

**Suggested change**
Load the Token page first.

**Additional Context**
![Screen Shot 2022-01-20 at 09 26 21](https://user-images.githubusercontent.com/49105975/150339504-446479c9-5234-499b-97ca-9f24dc1c781f.png)

**Comment by L03TJ3** [comment]
This has to be changed in the data studio itself, I don't know where it's managed...
but it is not part of this repository

**Comment by patpedrosa** [comment]
What do you mean by "this"? Dashboard loads correctly when accessed directly via http://dashboard.gooddollar.org/.

**Comment by L03TJ3** [comment]
@patpedrosa 
What I meant is that the issue DOES happen also when I directly go to the link, or to dashboard.gooddollar
and it didn't seem to solve anything for me when I loaded up the token page as first

at least on my screens (1920x1080) it always pushes the digits over each other on the token page

so to me, it seemed like a data-studio styling issue, which can only be changed in the document itself...
perhaps just a couple of pixels smaller font size?

![image](https://user-images.githubusercontent.com/6606028/150675886-98dad98e-8eac-4728-a49e-cc03229081a0.png)

**Comment by sirpy** [comment]
@L03TJ3 i fixed it. please test

**Comment by L03TJ3** [comment]
![image](https://user-images.githubusercontent.com/6606028/150678699-f8c7eb52-8996-4230-9081-74c9d045a10c.png)

if it is live on fi-qa, it's still the same
if I should test master locally? then I'll get back on this

**Comment by L03TJ3** [comment]
yes, sirpy fixed it

**Comment by patpedrosa** [comment]
@L03TJ3 Looking at the wrong bug

This is what I reported, not the overlapping percentages:
<img width="815" alt="Screen Shot 2022-01-23 at 12 17 06" src="https://user-images.githubusercontent.com/49105975/150685447-566ad58c-24ac-4057-a3c1-48fe1654fead.png">
:

**Comment by patpedrosa** [comment]
@sirpy Thanks, it's fixed on prod.
