### ISSUE TITLE
Add suggestions for social Media shares after succeeding with Swap and Stake transactions

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#126]
**Is your feature request related to a problem? Please describe.**
GoodDollar is a Social Impact investment protocol, so let's push to make investor actions more social.

**Describe the solution you'd like**
After swapping and staking (both GoodStakes and GoodDAO stakes) let's add a pop up window where we suggest user to post this action on social media (twitter & facebook are a must! Instagram Story is a nice to have).

So for each succeed action let's suggest to post on Social Media (including social media logos) the following:
- Swapping (only for buying G$s, not selling):
I just bought GoodDollars at goodswap.xyz to make the world better #InvestForGood

- Staking (Trust Fund/GoodStake)
I just staked [DAI|USDC] at goodswap.xyz to generate UBI for thousands of user and make the world better #InvestForGood

- Staking (GoodDAO)
I just staked GoodDollars at goodswap.xyz to make the world better #InvestForGood

**Comment by YpetrovAJ** [comment]
@sepu85 need to create the design here first of all, am I right?

**Comment by sirpy** [comment]
@YpetrovAJ yes please start with a design

**Comment by YpetrovAJ** [comment]
can you provide for us some references for templates for Twitter or Facebook sharing? we'll create the separate for each social media

@sirpy @patpedrosa

**Comment by sepu85** [comment]
hey @YpetrovAJ after the transaction is submitted you should add to the success message a message to share on social, placing social media buttons (image below is kovan fi-qa version or see issue #80 for further reference) 

<img width="554" alt="Captura de pantalla 2022-01-27 a las 11 56 31" src="https://user-images.githubusercontent.com/22507864/151345514-3490d6cb-9eea-4742-8eb2-99d30c04733f.png">

once the user select his/her preferred social media, this should link to his social media account suggesting the texts that I have submitted when opening the issue.

about template, as sirpy suggested, *please research how other websites are offering users to share something to social media and do something similar*

**Comment by YpetrovAJ** [comment]
[here](https://www.figma.com/file/qQnLAqI49HHbvHr1o1xD1a/GoodDollar?node-id=110%3A1210) you can check the design 

we've also added the templates for stacking and swapping in the social media (you can see it below) 

@sirpy @sepu85

**Comment by annastone-86** [comment]
It should include default messaging: 

"I just used my crypto for good to help fund crypto UBI for all with GoodDollar!"

**Comment by sepu85** [comment]
@YpetrovAJ regarding Anna's feedback, please include it in the first pop up, I mean:
<img width="228" alt="Captura de pantalla 2022-01-27 a las 20 40 46" src="https://user-images.githubusercontent.com/22507864/151431721-f3e6b4db-c63c-40d8-adfb-899d483118e8.png">

So just below Swap Completed, please include @annastone-86  suggestion, I rather say "You" instead of "I", so:

"You just used your crypto for good to help fund crypto UBI for all with GoodDollar!"

then, for the social post itself, please keep the original copy proposed at the opening of this issue.

**Comment by YpetrovAJ** [comment]
done

**Comment by sirpy** [comment]
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/7e0b5096-a061-460e-a020-b3dea9fb3611)

**Comment by sirpy** [comment]
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/1a9049ea-2295-436a-a285-cb2855b47983)

**Comment by YpetrovAJ** [comment]
@sirpy which link should we share after swapping/staking? just a link for https://goodswap.xyz/#/swap or something else?

**Comment by artqadev** [comment]
hi @sirpy 

fi-dev confirm
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/a229a3f5-3acc-48cd-9435-dbbf22f15432)
fi-qa is without social buttons (the popup didn't even change to "swap completed")
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/32a75c6a-97d8-49a7-8c62-0c231fa8fe53)

**Comment by sirpy** [comment]
@artqadev fi-qa needs to be deployed, you guys have setup the flow in the past
@DmitryIlchenko

**Comment by L03TJ3** [comment]
Recheck flow of sharing:
1. find solution to show socials when submitted modal is closed before confirmation
2. doesn't always show up when doing a swap

**Comment by L03TJ3** [comment]
Priority Fixes:
1. Copy button doesn't work in a live environment (does work local for me?)
2. Update copy text to copy icon (see slack)
3. Sharing socials don't show up for swapping transactions

**Comment by artqadev** [comment]
Hi @L03TJ3 
Verified on fi-qa:
![swapshape.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/6174ac48-6e08-4593-8c22-4b54a1bda5d1)
It looks good, but I'm not sure that the Copy button is actually clickable (works). Can you recheck it, please?

Thank you
