### ISSUE TITLE
mark USDC staking option as "Temporally Unavailable"

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#131]
After launching GoodDollarV2, @sirpy realized there was a bug in the USDC Aave staking smartContract that was preventing staker to get their G$ rewards.

While we launch the new smartContract, it is convenient to bring some clarity to users about why the stake button is unavailable.

So request here is to change text button (Aave USDC staking option) from `STAKE` to `Temporally unavailable`

**Comment by L03TJ3** [comment]
![image](https://user-images.githubusercontent.com/6606028/152152933-ed66b7dc-0bf1-46f8-8c14-f9956b0e5e92.png)

idea to make the button red & disabled?

**Comment by sepu85** [comment]
I find red color unnecessary here, please let the the current disable status with faint blue.

**Comment by L03TJ3** [comment]
Okay! is fixed now

**Comment by sirpy** [comment]
replaced by new staking contracts
