### ISSUE TITLE
(chore) install ceramic node on a VPS

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#146]
See instructions
https://developers.ceramic.network/run/nodes/nodes/#required-steps

## V1
- [x] use docker
- [x] make sure ports are open
- [x] demo

## V2
- [x] backup solution - connect ceramic with s3 + enable vultr snapshots 
- [x] monitoring (using our alibaba cloud monitoring)
- [x] make sure everything starts on vps restart
- [x] make a PR to join the network

**Comment by YpetrovAJ** [comment]
We've done all that things

Should we do there anything else? 

@sirpy

**Comment by admin-artjoker** [comment]
PR - https://github.com/ceramicnetwork/peerlist/pull/68
