### ISSUE TITLE
(Bug) uniswap routing and price impact seems incorrect

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#149]
When wanting to swap on mainnet WBTC to G$ the path shows:
WBTC -> ETH -> DAI and price impact of >1%
This doesnt make sense as a direct route for WBTC->DAI should exists and make more sense
Also when swapping 0.5 WBTC->DAI on uniswap V2(which is what we use) the price price impact is only 0.06%
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/b733c552-8495-47e4-998b-f20abb9616fb)

To check/fix
- [x] why isn't shorter route selected WBTC -> DAI instead of WBTC -> ETH -> DAI
- [x] verify that price impact we calculate for for the uniswap exchange is similar to what is seen on uniswap v2 interface
https://app.uniswap.org/#/swap?use=V2&chain=mainnet
- [x] once uniswap price impact is correct and verified, verify that how we calculate the combined price impact of token->dai at uniswap plus the price impact of dai->G$ on the reserve is correct

**Comment by sirpy** [comment]
@YpetrovAJ this is high priority

**Comment by L03TJ3** [comment]
Verified that the calculations are correct!
