### ISSUE TITLE
General mobile UI issues

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#157]
**Issues Description**
- [x] - General responsiveness problems (Staking / Portfolio Tables) (Priority)
- [x] - (IOS) top navbar gets pushed outside of screen after filling in swap amounts / actually swapping
- [x] -  Swap balances should be shown outside of the input box

**Additional Context**
Tested on Android v11, chrome browser / desktop chrome with device toggle
IOS 15.3.1

Example for stake tables and general margin/padding
![image](https://user-images.githubusercontent.com/6606028/164003323-63256a76-9aab-48ad-a0f8-9f41773539dc.png)

**Done**
- [x] - Refactor menu to either slide-in/slide-down OVER content
    --> now it pushes content down
    --> clicking menu-item should close menu after

**Comment by artqadev** [comment]
Hi @L03TJ3 
Again, I can see the changes on fi-qa, but not on dev. Is this expected or acceptable? 

Thanks!

**Comment by L03TJ3** [comment]
Yes.
so what's on fi-dev currently is everything up to the new flow for connecting a wallet / social shares.
What's currently on fi-qa is all the styling updates after.

**Comment by L03TJ3** [comment]
to clarify.
Yes, it is expected currently. If it is acceptable is up to debate while we are refining the work-flow a bit :)

**Comment by artqadev** [comment]
I am satisfied, just needed to clarify :)

TY!

**Comment by artqadev** [comment]
Prod checked
