### ISSUE TITLE
Wallet Connect issues

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#158]
**Bug Description**

- [ ] - 0. **PRIORITY** Currently, when connecting with wallet-connect to desktop, nothing is able to load (see screenshots)
- [ ] - 1. **PRIORITY** Wallet connect unable to get network on production

- [ ] - 2. Approval/Confirmation isn't always sent to the connected wallet
- [ ] - 3. Local storage is not always emptied after disconnect, and the user becomes unable to connect another wallet until the cache is emptied
- [ ] - 4. switching networks doesn't work with mobile MM wallet
   --- This does work for AirdropUI

**Steps to reproduce**
issue 1: (both mainnet & fuse)
1. Connect to goodswap with wallet-connect
2. See balance information not being loaded

Issue 2: (noticed with MM wallet, might be with others as well)
1. Connect any wallet through wallet-connect with the dapp
2. Make a transaction
3. The tx confirmation requesting does or does not appear on the mobile wallet
4. Repeat because sometimes it does, sometimes it doesn't work

Issue 3: (Noticed with trust wallet & metamask)
1. Connect a mobile wallet to goodswap on desktop
2. Disconnect
3. Look for the key 'walletconnect' in local-storage
4. Sometimes, this is not deleted properly.
5. refresh and click connect wallet again.
6. Old connected wallet is used even though the connection doesn't exist anymore. User is unable to connect with other wallet until they empty local storage / hard-refresh

Issue 4: (Mobile MM Wallet)
1. Connect with wallet-connect to goodswap
2. Switch network
3. Dapp should be triggered on chainChanged, just like when using desktop wallet

**Additional Context**
Test env --> Tested on Android v11

Issue 1 error:
![image](https://user-images.githubusercontent.com/6606028/156777737-b9a4d3cc-f14c-44a1-953c-c66e3740a67b.png)

**Comment by sirpy** [comment]
@L03TJ3 can you describe the flows to reproduce those issues?

**Comment by L03TJ3** [comment]
I'll close this, as either the issues are defined in new ones / or will be solved by the new onboard update
