### ISSUE TITLE
MM Browser can't open Fuse directly

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#159]
**Bug Description**
When your mobile MetaMask wallet is connected to Fuse, it cannot (always) open goodswap.xyz with the app browser

**Steps to Reproduce**
1. Close all existing tabs in MM
2. Restart the MM app
3. Set network to Fuse
4. Open browser and go to goodswap.xyz
5. Error 'We couldn't resolve that ENS name (see screenshot below

**Expected Behavior**
You should be able to access goodswap.xyz with either fuse or ethereum selected

**Additional Context**
1. When you first visit goodswap with the mainnet selected as network and then switch, you are able to visit goodswap without error.

2. Reference  
bug: https://github.com/MetaMask/metamask-mobile/issues/2332

3. Screenshot of error

![image](https://user-images.githubusercontent.com/6606028/156339820-79a08264-6517-469f-aea8-2fb7bc039be8.png)

**Comment by sirpy** [comment]
metamask issue
