### ISSUE TITLE
'Failed to fetch multicall chunk' after switching chains several times

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#169]
**Bug Description**
An error occurs after several times switching chains where the switched network is detected, but the request data
is not updated accordingly so it tries to fetch data from the previously connected chain

**Steps to Reproduce**
1. Connect your wallet to the app
2. Switch chains a couple of times
3. console should show error shown in image below

**Expected Behavior**
The error should not occur, after chain is switched it should fetch from the updated chainId.
also its unclear if it breaks anything.
ie. balances are still updated correctly, and transactions can be made just fine

**Additional Context**
![image](https://user-images.githubusercontent.com/6606028/162511083-ff3a57d1-6426-4771-8a37-902fe3c69cfc.png)

Best to test and fix this while using the newly added block-native onboard connection.
working version can be found on branch feature/GoodProtocolUI-163

**Comment by sirpy** [comment]
nothing we can do
