### ISSUE TITLE
(Chore) setup basic build flow

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#17]
- [x] setup basic testing. currently testing should pass if projects builds for production correctly otherwise fail
- [x] code checks: add linter
- [x] bundle size check, should put some warning if bundle size grows above limit or is significantly larger than previous build

**Comment by thaddaeusus** [comment]
Integrated [BundleMon](https://github.com/LironEr/bundlemon-github-actions) for size checks for now.

**Comment by sirpy** [comment]
there's some error in the build process
