### ISSUE TITLE
(Devops) ensure servers monitoring on alibaba + status page

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#181]
Make sure we monitor the following servers on alibaba
- [x] ceramic
- [x] facetec-prod
- [x] fuse validator

Use our betteruptime account to monitor:
- [x] ceramic endpoint
- [ ] facetec endpoint
- [ ] cloudflare sms verifier

**Comment by sirpy** [comment]
@johnsmith-gooddollar any other services we need to monitor? any 3rd parties services?

**Comment by johnsmith-gooddollar** [comment]
@sirpy ceramic dashboard (strapi) 
goodceramic-(dev|qa-next).herokuapp.com/admin

**Comment by DmitryIlchenko** [comment]
@sirpy 
Have a questions:
1. On Alibaba we see only ceramic (we added it there) and "facetech-prod". What is a fuse validator server? We need access to it in order to add it to Alibaba. Could you provide this information to us?

2. What is meant by cloudflare sms verifier? what is the task?
