### ISSUE TITLE
Extend Google Analytics

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#183]
**Description**
Currently, we are only tracking page visits with GA. This needs to be extended to cover the following:
- [x] When someone clicks on the button "Claim UBI"
- [x] When someone clicks "approve" and also "swap"
  - [x] Collecting what they swap and the value will be a very good additional info.
- [x] When someone clicks on "stake"
   - [x] Collecting how much G$ they stake will be a very good additional info.
- [x] When someone successfully has submitted its transaction
- [x] When someone withdraws their stake

The event(s) are pushed to the dataLayer array, which needs to be added to the header:
`<script>
  dataLayer = [];
</script>`

**click events IE**
`dataLayer.push({'event: 'swap', action: 'confirmSwap', amount: '2500', tokens: '[input, output]'})`
`dataLayer.push({'event': swap', action: 'approveSwap'})`
`dataLayer.psuh({'event': 'claim' action: 'claimUBI'})`

**submitted events (IE. when the submitted dialog box appears for either swap/stake)**
`dataLayer.push({'event': 'swap' action:'submittedSwap'})`

**Comment by drptiago** [comment]
When someone clicks on the button "Claim UBI"
`dataLayer.psuh({'event': 'claim' action: 'claimUBI'})`

The event will be trigger when click in the button below:
![claim](https://user-images.githubusercontent.com/62208156/170372768-e2349176-bb68-4ca4-9328-d48d01c2279f.png)

**Comment by drptiago** [comment]
When someone clicks "approve" and also "swap"

The events will be trigger in the flow below, onclick:

`dataLayer.push({'event': swap', action: 'approveSwap'})`
![approve](https://user-images.githubusercontent.com/62208156/170373121-be882330-7193-4da5-84b4-a2708184381e.png)

`dataLayer.push({'event': swap', action: 'swap'})`
![swap](https://user-images.githubusercontent.com/62208156/170373252-9313271e-1a84-41b2-a1b0-b10c7f41e55f.png)

`dataLayer.push({'event: 'swap', action: 'confirmSwap', amount: '2500', tokens: '[input, output]'})`
![confirm](https://user-images.githubusercontent.com/62208156/170373372-9be5b541-975f-4ce0-9d5a-811fb8b5a70b.png)

dataLayer.push({'event': swap', action: 'swapSubmitted'})
In this last one "submitted" the best will be when the dialog box appears.
![submitted](https://user-images.githubusercontent.com/62208156/170373421-c113c2fd-b707-413f-9df8-319f37a20503.png)


If we have the option to track the cancel/reject will be very good too.

**Comment by drptiago** [comment]
When someone clicks on "stake"

The events will be trigger in the flow below, onclick:

`dataLayer.push({'event': 'stake', action: 'stake'})`
![stake (1)](https://user-images.githubusercontent.com/62208156/170374531-91a15568-c777-4a23-acd4-b082935f9f0a.png)

`dataLayer.push({'event': 'stake', action: 'approveStake'})`
![aprove stake (1)](https://user-images.githubusercontent.com/62208156/170374636-a4dd6f81-d512-485e-a5c1-b79c5eb3ba27.png)

`dataLayer.push({'event': 'stake', action: 'depositStake'})`
![deposit (1)](https://user-images.githubusercontent.com/62208156/170374790-422c529d-b15a-469f-9279-7bf773238d69.png)

`dataLayer.push({'event': 'stake', action: 'awesomeStake'})`
In this last one "awesome" the best will be when the dialog box appears.
![awesome (1)](https://user-images.githubusercontent.com/62208156/170374843-e9d8215d-d486-4d2f-8758-30e3c3b7a9d3.png)

**Comment by drptiago** [comment]
I added the images here to be more clear the desired behavior. 

Be free to make suggestions or if you have any questions.

**Comment by sirpy** [comment]
@drptiago i thought the reason we added the tag manager is so that you can capture those events yourself using css matching like so:
https://www.simoahava.com/analytics/capturing-the-correct-element-in-google-tag-manager/

**Comment by drptiago** [comment]
We are successfully tracking some events in goodswap using GTM @sirpy  , but some events I can't track in Google Tag Manager because of the way the site is made ( react ).  

This is the container who already have the events I can track directly in GTM without the data layer:
https://tagmanager.google.com/?authuser=1#/container/accounts/4420848896/containers/65741254/workspaces/10

**Comment by sirpy** [comment]
@drptiago see on slack...

**Comment by drptiago** [comment]
### To summarize the events implemented


**Stake**
1 - stakeStart {network, protocol, amount}
2 - stakeApprove {network, protocol, amount}
3 - stakeDeposit {network, protocol, amount}
Done - awesomeStake {network, protocol, amount}


1 - withdrawStart {network, protocol, amount}
2 - withdrawAprove {network, protocol, amount}
Done - withdrawSuccess {network, protocol, amount}


**Swap**
1 - approveSwap {network, tokens, amount, buy/sell}
2 - startSwap {network, tokens, amount, buy/sell}
3 - confirmSwap {network, tokens, amount, buy/sell}
Done - submittedSwap {network, tokens, amount, buy/sell}


**Claim**
1 - claimStart
Done - ClaimSuccess


**Site navigation ( clicks in lateral menu)**
GOTO_DASHBOARD
GOTO_SWAP
GOTO_STAKE
GOTO_PORTFOLIO
GOTO_WALLET
GOTO_BRIDGE
GOTO_DOCS


**General demographics** ( age, gender, countries, languages) and **tech information** ( OS, Device, Platform) are also collected.
