### ISSUE TITLE
GDX information is shown outside scope

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#187]
**Bug Description**
When swapping on mainnet (or test-net), the GDX information is shown as a separate block.
this should be under its designated information icon

**Steps to Reproduce**
1. Go to /swap
2. set swap amount
3. gdx information shows besides swap screen

**Expected Behavior**
Both the gdx and exit contribution information should be with the respective information icon below the swap screen

**Additional Context**
![image](https://user-images.githubusercontent.com/6606028/171794626-c2d2c0c9-c417-4307-811e-7ccf450bcdbc.png)

**Comment by imanov-elchin** [comment]
![image.png](https://images.zenhubusercontent.com/620d0858dd7f2f4a552b7a25/a288c767-3734-41fb-ac50-fd8f85181adc) 

Also added tip icon to confirmation modal window
