### ISSUE TITLE
Add indicators that balance/swap amounts are loading

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#188]
**Bug Description**
Currently when a user navigates to goodswap and connects its wallet, 
there are no indicators anywhere that certain parts (wallet balance/swap amount) of the application is loading data
it suddenly starts to display/pop-up after successfully being loaded

**Steps to Reproduce**
1. Go to goodswap.xyz
2. connect your wallet
3. It might take a few seconds to show wallet-balance
  - when entering the swap amount, it takes a few seconds to show the received amount

**Expected Behavior**
It should be clear to the user that the app is loading data.
This could also make it more clear when data is unable to be loaded.

- [x] Add loading indicator for balance (top-bar native balance / sidebar wallet-balance)
- [ ] Add failed indicator to show when it was not able to do so
- [x] Add an indicator to show the received amount is being calculated

**Comment by L03TJ3** [comment]
Balance
![image](https://user-images.githubusercontent.com/6606028/172263809-681b5fb0-efd0-40f6-9d48-f244a5e48574.png)

Calculating swap amount
![image](https://user-images.githubusercontent.com/6606028/172263894-df700700-c884-4223-99f4-d51b63a148ce.png)

**Comment by artqadev** [comment]
Prod checked
