### ISSUE TITLE
User should be able to connect his wallet

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#2]
Add a wallet connection component
- [x] see snapshot.page connection options (you can copy form their repo the code)
- [x] keep state if user is connected or not, some pages/data will be blocked if not connected
- [x] keep set of valid networks (currently fuse/ethereum - network ids 122 and 1) if user is connected to a different one then show error message (see snapshot and uniswap)
- [x] multiple providers

**Comment by sirpy** [comment]
libraries that might be relevant @thaddaeusus 
https://github.com/Web3Modal/web3modal
https://docs.blocknative.com/onboard

**Comment by sirpy** [comment]
- no error message when user uses a wrong network, and nothing happens when user presses connect and his metamask is currently on an unsupported network

**Comment by thaddaeusus** [comment]
Works as expected: 
- if **connected** wallet changed to wrong network: disables operations and shows "**Wrong network**" on top right;
- **not connecting** at all with wrong network. 

Can add extra a) notification toast or b) popup message (like fuseswap) to clarify state for user.

**Comment by sirpy** [comment]
@thaddaeusus also connect the PR to the issue on zenhub
