### ISSUE TITLE
Project: set up husky

### ISSUE THREAD

**Issue by ghost** [GoodDollar/GoodProtocolUI#206]
Description: 
Set up project to run lint-staged before commiting the code. 

Tech description: 
Make sure that you registered lint-staged script onto pre-commit hook. And it runs every time when you try to commit your changes.

**Comment by imanov-elchin** [comment]
@L03TJ3 I also propose to add conventions to our commit messages. I have notes from past experience. So, 

We can use this template 
<type>(<scope>):<message>

**Type** - required.

Valid types:

- feat (feature)
- fix (bugfix)
- docs (documentaion)
- style (style guide)
- refactor (refactor)
- test (adding tests)
- chore (general(common) - changes in package.json, .npmrc etc)

**Scope** - required.

- summary information like client or server. Or more precisely config or sagas
- it can be module name which is in development 
- or if there is multiple modules in development we can assign scope to *

**Message**
Short description of the change

**Comment by L03TJ3** [comment]
@imanov-elchin approved!

**Comment by johnsmith-gooddollar** [comment]
done in #263
