### ISSUE TITLE
UI Organism: user-friendly progress indicator

### ISSUE THREAD

**Issue by thaddaeusus** [GoodDollar/GoodProtocolUI#22]
Compose `ActionLog` component acting like Github Actions report:
![image.png](https://images.zenhubusercontent.com/604530e1151cf29e78f2e5e3/6a19216b-027f-4053-8dff-62711144cf59)

Use it with Swap and Claim operations as progress indication.

**Comment by sirpy** [comment]
@tomerGD need to explore this option
