### ISSUE TITLE
Change handling of unsupported network

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#227]
**Bug Description**
Currently, an alternative modal is shown when a user clicks on account details when connected to an unsupported network.
The regular modal should be shown instead. This doesn't work out-of-the-box cause of fetching account information like transactions list.

**Steps to Reproduce**
1. Go to goodswap
2. connect a wallet
3. switch to any unsupported network
4. click on the red unsupported network button on the top-right

**Expected Behavior**
A minimal version of the account details should be shown for changing/disconnecting accounts.

- [ ] Minimal account details 
- [?] switching from unsupported > supported network should automatically close the onboard pop-up indicating user should switch (fix to be done by onboard)

**Comment by patpedrosa** [comment]
<img width="334" alt="Screen Shot 2022-10-31 at 12 19 21" src="https://user-images.githubusercontent.com/49105975/199043753-1d164dd5-8f9b-47ed-8b46-c64e866bc754.png">

**Comment by L03TJ3** [comment]
Closing in favor of #247
