### ISSUE TITLE
Nativebase should have a G$ theme

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#233]
https://docs.nativebase.io/

- [x] define basic fonts
- [x] define basic headers and text sizes
- [x] define basic colors

### Optional
- [x] define basic components look and feel

**Comment by patpedrosa** [comment]
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?node-id=2127%3A76968

**Comment by L03TJ3** [comment]
Design system will have a small update soon

**Comment by L03TJ3** [comment]
This has been implemented
