### ISSUE TITLE
FVFlow should wait until user is whitelisted

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#234]
on GoodDAPP FVFlow mode:

- [x] before redirecting user back to calling app, wait for 30 seconds or until user is whitelisted
- [x] show a spinner and a message "Please wait until your verification is completed"

**Comment by sirpy** [comment]
@johnsmith-gooddollar this needs to be tested + add spinner

**Comment by johnsmith-gooddollar** [comment]
ok

**Comment by johnsmith-gooddollar** [comment]
@alt-a1r need to test it with #230

**Comment by johnsmith-gooddollar** [comment]
@vldkhh Please, actualise this

**Comment by L03TJ3** [comment]
(fi-qa)
![IMG_FIQA](https://user-images.githubusercontent.com/6606028/214384249-eaa4c7ce-d701-4a63-9e19-6da852f62bd1.png)

(fi-dev)
![IMG_FIDEV](https://user-images.githubusercontent.com/6606028/214384288-44221ed2-9df0-4db7-8267-dd14d763c814.png)

**Comment by vldkhh** [comment]
@L03TJ3 @johnsmith-gooddollar looks like it works properly on dev. 30-sec call down  is shown after FV success

**Comment by vldkhh** [comment]
successfully passed FV and claimed both chains on prod
