### ISSUE TITLE
FVFlow should allow user to give up

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#235]
on GoodDAPP FVFlow mode:
- [x] if user failed 3 times, show also a button "I give up"
- [x] if user presses it show modal. "What happened?", 
- [x] once user selects and option redirect back to app with `verified=false`
    - Camera issues
    - Unable to put my face in the Oval
    - It says I have a twin
    - It keeps asking me to try again
- [x] report using analytics the user issue choice

**Comment by johnsmith-gooddollar** [comment]
@sirpy have a question "report using analytics the user issue choice" 

1. where it should be done ? on goodprotocolUI side or on the gooddapp ?
2. regarding gooddapp - we do not have analytics initialized during fv flow. need to add it, also could fv app use analytics creds from gd app or we have to create new ones ?
3. also how we can identify user ? using fvsig + firstName + account received from FVFlowContext ?

**Comment by sirpy** [comment]
1. gooddapp side
2. yes same creds, just need to add param fvflow:true sent to analytics
3. account is  enough
