### ISSUE TITLE
User should have his wallet topped in the background

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#238]
- [x] in sdk-v2: a hook that triggers on user native balance change
- [x] if user is on fuse/celo and his native balance < 150k * chainGasPrice, then issue request to backend topWallet endpoint with account+chainId
- [x] use new hook on protocol UI

**Comment by johnsmith-gooddollar** [comment]
@alt-a1r @roma-hladilka Once https://github.com/GoodDollar/GoodWeb3-Mono/pull/15 will be merged please implement the last one point

**Comment by johnsmith-gooddollar** [comment]
@roma-hladilka you could proceed with this task

**Comment by L03TJ3** [comment]
![image.png](https://images.zenhubusercontent.com/5f68aed4c344a37886854fbd/fee124f1-a02f-4063-aa95-9007974f42da)

**Comment by vldkhh** [comment]
@johnsmith-gooddollar @L03TJ3 ^^^
The wallet is not topped after connecting to the chain

**Comment by johnsmith-gooddollar** [comment]
@vldkhh it was a server issue, hot fixed: https://github.com/GoodDollar/GoodServer/commit/f0b7c0510f333ffab0610fef71aa8b103f66dfd3

**Comment by vldkhh** [comment]
@johnsmith-gooddollar @L03TJ3 verified on production via the new account 
![Snag_3bb1dc.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/199f8ed5-71cb-4b02-a69e-5b72ddcac815)
