### ISSUE TITLE
Claim should be triggered automatically when user is first whitelisted

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#241]
- [x] Once user finishes FV, when he comes back to the claim screen, the claim TX should be triggered automatically
- [x] A special modal should be shown to user explaining about the first claim and that he needs to sign the tx on his wallet

see:
https://gooddollar.invisionapp.com/freehand/Good-Protocol-UI-V2-Wireframes-88jFb33ex

**Comment by L03TJ3** [comment]
In theory it is fixed and the claim works
But the verified param is never removed from URL, so it keeps requesting to claim when you for example switch pages and/or reload

**Comment by sirpy** [comment]
if this was moved to a new issue then this needs to be closed @L03TJ3
