### ISSUE TITLE
Celo should be the default sidechain

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#242]
- [x] add Celo to the available networks at the network selector button
- [ ] Walletconnect should ask for Celo by default (verify our wallet connects to Celo by default when connecting with walletconnect)
- [ ] Claim button (web3action) should request Celo by default
- [x] verify other buttons still ask correctly to switch to mainnet/fuse when connected to Celo
- [x] Optionally: when connected to wrong blockchain ie (not fuse,mainnet,celo) it should request to switch to Celo. (what's the current behaviour?)

**Comment by L03TJ3** [comment]
Since the moving to the sdk package the unsupported network broke. (#227)

but it now automatically asks one time to connect to mainnet (as this was set as default)
so the default could just be changed to 42220 for this

An actual fix has not been made yet

**Comment by sirpy** [comment]
i dont understand how this is related to 227, which is simply about the red button that it should allow the user to disconnect.
this ticket outlines exactly what needs to be done, if you have questions regarding any of the checkboxes please be more specific.

**Comment by L03TJ3** [comment]
Your right, the 227 was not necessarily related to my comment as well.
The latter part was about the Optionally point.
current behavior:
when switching to/or loading with a wallet to an unsupported network, the setChain automatically calls for switching to mainnet (as this was set to default)

**Comment by L03TJ3** [comment]
Time-estimate: 2 days

**Comment by L03TJ3** [comment]
Specifically:

- Recheck if it requests celo through wallet-connect
- Recheck if it asks for celo when on an unsupported network
