### ISSUE TITLE
Reference_Microbridge component design for GoodDapp

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#252]
- Every bridge transfer requires a Relay - someone to execute the transfer on the other chain.
Relay
   - relayer gets 50% of the bridge fee
   - this will usually happen automatically by us or by others running a relayer
-  

### Bridge + History/Relays
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/361d2634-052d-4d08-a83d-6f7ef9342a08)

### Bridge start
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/33e4328c-279a-4dad-b5eb-ee872a9c75fc)

### Bridge waiting for relay
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/68afa6dd-a736-4dd5-aa2f-7fbcb141c2a5)

### Bridge relay success
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/4224b24d-1028-40df-baee-c0603e32e0e7)

### Bridge Error
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/1ae6a1e2-a73a-4c6f-9d4c-d0d30fabe8dc)

### Bridge status info popover
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/7ce2b025-2b20-4e1d-8c08-3559a6e30c12)

**Comment by sirpy** [comment]
@patpedrosa this is the fully functional UI that will need to be designed

**Comment by L03TJ3** [comment]
@decentralauren again assigned you, part of the never released microbridge implementation on gooddapp.
Showed screens are not finalized and what has been implemented has a different look. (not sure where those designs are...)

**Comment by L03TJ3** [comment]
![image](https://github.com/GoodDollar/GoodProtocolUI/assets/6606028/8c98b3d3-246a-4b9b-8cfc-4dde7e310e27)

**Comment by decentralauren** [comment]
Need to consider (both shown in Hadar's original ticket):
[ ] How to display fee structure
[ ] How to display transaction status / processing
@decentralauren

**Comment by L03TJ3** [comment]
@decentralauren there seems to be confusion about what should be included or not in the microbridge.
Below is the screen of all that we show in the current implementation
![image](https://github.com/GoodDollar/GoodProtocolUI/assets/6606028/4bbf88ec-d5dc-4c29-bca6-dcfa4f76bb7b)

So still the questions are:
1. should we show the fee (and the why of the fee?)
2. should we include transaction history or not
3. Self-relay = don't wait for a third-party to confirm/verify your transaction, do it yourself by doing a relay-transaction (cost-gas)
--- Last time we went over this (a year ago) it was decided to not enable this feature. Should we revisit that decision?

All based around 'What should be included/excluded' when designing a new/updated screen for the widget

cc: @SanaJamm

**Comment by decentralauren** [comment]
[Closed, replaced with this ticket to include updated designs](https://github.com/GoodDollar/GoodProtocolUI/issues/558)
