### ISSUE TITLE
Monorepo and GoodSwap should have Eslint installed & configured to be ran before each commit

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#263]
- [x] install eslint with TS plugin
- [x] configure
- [x] fix lint issues on monorepo
- [x] check prettier integration
- [x] add lint-staged & husky
- [x] do steps above for GoodSwap

**Comment by johnsmith-gooddollar** [comment]
Opened PR for monorepo: https://github.com/GoodDollar/GoodWeb3-Mono/pull/31/files

**Comment by L03TJ3** [comment]
- [ ] - Prettier rules are not applied or tested against through lint-staged on pre-commit hook
Context:
Whenever you run eslint --fix manually it shows you correctly if prettier formatting has not been applied, and fixes accordingly
the same rules are not giving an error and/or are not fixed when its run through pre-commit hook

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 

1. "plugin:prettier/recommended", was missing in the configurations list to extend from
2. no prettier rules were specified, "prettier/prettier": "warn", was added

Fixed in the master branch  at both protocol app and monorepo
https://github.com/GoodDollar/GoodProtocolUI/commit/f050fffbe0b75a1a9cd2bc3b502ac56eab7e775f
https://github.com/GoodDollar/GoodWeb3-Mono/commit/29111ce7041a4dc67dc3e164183b1e2e85734ebd

**Comment by johnsmith-gooddollar** [comment]
Tested with one-liner `export function add(n:number):number{return n+1}`- it was successfully expanded and reformatter via prettier during commit

**Comment by L03TJ3** [comment]
Works, verified
so done
