### ISSUE TITLE
Analytics event improvements

### ISSUE THREAD

**Issue by drptiago** [GoodDollar/GoodProtocolUI#268]
**Goal:**
1 - Standardize the event names to better understanding and also make ease to maintain
2 - Make sure we are cleaning the data layer in each new event
3 - Fix some wrong properties/events

**Description:**
1 - Some events are not following the same logic name, the goal here is standardiz and also keep the same names we sent to Google and Indicative. To fix this we will follow: "start | approve | confirm | success" standard.

Ex:
**Savings:**
savings_start
savings_confirm
savings_success

**Swap:**
swap_start
swap_confirm
swap_success

**Claim:**
claim_start
claim_success

1.1 - Some events like the "claim rewards" must have a different name, right now it is "claim_success", the same name of the event to claim UBI.

**claim rewards**
savings_withdraw_rewards_claim_start
savings_withdraw_rewards_claim_confirm
savings_withdraw_rewards_claim_success

---------------------------------------------------------------------------------------

2 - After sending one event the data layer keeps the data and when we send a new event some properties are sent together. Ex: An event who does not have the "amount" property is sent an " amount".

To fix this is just cleaning the data layer in each new event.

--------------------------------------------------------------------------------------

3 - Some events have the wrong properties, as always send network FUSE, instead CELO.
3.1 - Some actions, as the claim inside the claim page, is not triggering the event.
3.2 - In this sheet we have all events and a summary with all the names in the new standard format in the Column B (Event Name) with the names we need to send in the "action" and observations about wrong property/behavior in the Column E ( FI-DEV)
https://docs.google.com/spreadsheets/u/1/d/1nTiU5h2XtsGhJ8Vi0USn-B5jnUSMWs5OEhjwPfatthA/edit#gid=1010408646

**Observation:**
As aligned with Hadar we will not use Amplitude Analytics in GoodSwap, only Google Analytics and Indicative Analytics.

**Comment by L03TJ3** [comment]
1. added note: for ubeswap/celo we have to find an alternative in order to capture the swap events, but also need to make sure it doesn't get send twice on the other chains

**Comment by L03TJ3** [comment]
all work-in-progress events should be tackled now https://docs.google.com/spreadsheets/d/1nTiU5h2XtsGhJ8Vi0USn-B5jnUSMWs5OEhjwPfatthA/edit#gid=1010408646

Swap events for now only for fuse/mainnet
need to find separate solution for catching ubeswap events

**Comment by L03TJ3** [comment]
The events needed to be added for new features are:
[ ] - micro_bridge_start (GoodDesign/MicroBridge.tsx)
[ ] - micro_bridgesuccess (Not sure... need to check if the transaction made is being picked up by TransactionUpdate in UI, else GoodDesign/MicroBridgeController)
[ ] - swap_start / swap_success on celo (todo @L03TJ3 verify with ubeswap dev  if this can be added)
[ ] - wallet_connect_start/success (discuss with @drptiago )

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 started work here https://github.com/GoodDollar/GoodWeb3-Mono/pull/42

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar 
1. 👍 
2. okay!
3. swap components is all legacy in sdk-v1. Ubeswap is not yet moved to good-design since there are not many style options anyway. I am sending a message now ube devs to see if we can do something around events

**Comment by L03TJ3** [comment]
@drptiago 
Last requested changes can be tested on fi-dev
