### ISSUE TITLE
GoodSwap should have 'torus + google' option to connect wallet

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#272]
![image.png](https://images.zenhubusercontent.com/6135d0416eed5f7809f4ee6b/eaffe705-328d-4cef-b1e9-67ef4200f6ad)

ask @patpedrosa for more details

**Comment by sirpy** [comment]
@L03TJ3 wasnt that fixed already?

**Comment by L03TJ3** [comment]
Yes, up untill the label got changed from 'Powered by Web3Auth' to 'Web3Auth'
why I flagged it as a 3 minute fix
only need to update the label name in supported labels

**Comment by L03TJ3** [comment]
Hotfixed to prod and is working again
