### ISSUE TITLE
GoodSwap should use onboard package

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#277]
https://www.npmjs.com/package/@web3-onboard/web3auth

**Comment by L03TJ3** [comment]
![image](https://user-images.githubusercontent.com/6606028/210012953-01a21d00-be57-4014-8900-e3c672cdf4aa.png)

With no customization ability's to which login methods we want to support (or styling for the ones interested)
I suggest going the same route as done with ZenGo (meaning, customized module based on existing implementation. Zengo/WalletConnect)
So I suggest go forward with implementing openLogin from our sdk

@patpedrosa @sirpy @johnsmith-gooddollar 
All agree?

**Comment by L03TJ3** [comment]
Time estimate: 2 days (ish)

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 I agree.

**Comment by sirpy** [comment]
@patpedrosa are we sure we want that extra work instead of showing the regular web3auth modal with all the social login options.?
We are talking about 1-2 hours integration vs 2 days

**Comment by patpedrosa** [comment]
The purpose of implementing web3auth is so that on the Connect Wallet screen, a non-web3 user sees at least 1 recognizable option (the very first one, ideally) so they can at least have a shot at claiming on GoodSwap.

If it's not recnognizably something that they have seem before, then it will have no effect.

The wireframe shows clearly what we are going for and what's important (i care about this first screen - what happens later, what tech we use... i don't care):

<img width="256" alt="Screen Shot 2022-12-22 at 08 56 45" src="https://user-images.githubusercontent.com/49105975/210226756-1baf3d85-2f73-47d4-be63-ab07284451df.png">

Also, please keep in mind that we also need to add GoodDollar wallet and Valora to the Connect Wallet list (points to wallet connect) for the Celo launch.

**Comment by patpedrosa** [comment]
Going forward, let's make sure that when we pick 3rd party tech it allows for easy customization. This is the 2nd or 3rd time we're having UX issues with tools. (blocknative, ubeswap...)

UX is critical to us - we're not dealing with web3 native people and we need to be able to do at least the **minimum** amount of custom styling work to support the community.

**Comment by L03TJ3** [comment]
Okay, just pointing out that what you are requesting will take more dev-time then the plug&play options provided to us by the 3rd parties

But I believe to read now that the choice has been made to do spent the time necessary for customized modules in onboard

**Comment by sirpy** [comment]
There's not always a multiple solutions that enables choosing something that's "customizable" just the way you want it.
Please look at giveth.io they have different social recognizable buttons that they all then open the same torus popup. Is that good enough?

**Comment by patpedrosa** [comment]
> There's not always a multiple solutions that enables choosing something that's "customizable" just the way you want it.

It's not "just the way I want it" - it's what the user needs.



> Please look at giveth.io they have different social recognizable buttons that they all then open the same torus popup. Is that good enough?

As I said above - the user needs to see something they recognize. I don't care which tech or where it points. The connect screen wallet just needs to show at least 1 web2 social login option.

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 Please

1. describe the issues we currently  have
2. link your working demo app

**Comment by johnsmith-gooddollar** [comment]
@johnsmith-gooddollar
Package for torus has now been updated to the one which fixes switching chain (internally)
To research what happens on Protocol-UI,

publish this branch/sdk-v2 with yalc
Go over to ProtocolUI branch 272-add-social-login , run yalc add && yarn install (will update yalc package)
start dapp and connect wallet with torus
click in AppBar on network, and switch chain
torus screen should open with request to switch chain
Torus wallet itself is switching/switched (can be verified by wallet in bottom-left corner)
our UI doesn't switch over/gets stuck on last chain

**Comment by L03TJ3** [comment]
Switch chain seems to work.
But public fuse rpc is being blocked, so after switch it cannot get data.
asked torus dev for clarification
