### ISSUE TITLE
G$ Decimals should be dynamic based on token

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#284]
On Celo we might have an 18 decimals G$ instead of the 2 we have on ethereum/fuse
Decimals matters in:
- display: wherever we display G$ amount that we read from a contract we divide by (100/1e2) to convert from decimals to wei
- input: wherever we request user input in G$ we then multiply by (100/1e2) to convert to wei

Possible places to change
- G$ balance display: global balance box, balance shown in inputs (bridge, savings)
- G$ inputs: savings, bridge, governance staking

####In bridge notice that when you switch chains it should refresh the decimals from the correct change contract

Lewis already mapped some of the places that needs to be modified

**Comment by L03TJ3** [comment]
Definition of tokens: https://github.com/GoodDollar/GoodWeb3-Mono/blob/39f7be7a4c7c6cb523a383104a335b24eb6b7bf0/packages/sdk-v2/src/sdk/constants.ts#L52

Existing hook for getting all G$ Balances (above this hook is already a general method for tokens btw): https://github.com/GoodDollar/GoodWeb3-Mono/blob/39f7be7a4c7c6cb523a383104a335b24eb6b7bf0/packages/sdk-v2/src/sdk/base/react.ts#L145

Above method for tokens already used in sideBar -->
https://github.com/GoodDollar/GoodProtocolUI/blob/b98cea979104ff12deff22816b68e2fa20fc21d6/src/components/SideBar.tsx#L197

As for places, they are already described by @sirpy 
I don't think governance is relevant now (no need to change anything involving SDK-v1).

Global balance box: (UI) SideBar.tsx
MicroBridge: (mono) GoodDesign
Savings: (mono) sdk-v2 / (UI) savingsmodal
Swapping: (UI) SwapCelo

**Comment by L03TJ3** [comment]
Moved final todo-s in new issue #293
