### ISSUE TITLE
MicroBridge should work with the new SuperGoodDollar

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#289]
The updated bridge will now work with the new "SuperGoodDollars" on Celo that are 18 decimals
- [x] update to latest bridge-contracts/sdk packages
- [x] #294
- [x] verify 18 decimals are displayed correctly 
- [x] bridge works as expected with decimal conversion

**Comment by L03TJ3** [comment]
This can be verified and tested on fi-dev as we speak (going over it myself in a few)

**Comment by sirpy** [comment]
@L03TJ3 yes but you need to upgrade to the latest bridge sdks

**Comment by L03TJ3** [comment]
yes, just seeing that point!

**Comment by L03TJ3** [comment]
General support for 18 decimals, and bridge specific support is now split into two parts.
Protocol part has been moved to: https://github.com/GoodDollar/GoodProtocolUI/issues/293

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 please tell @vldkhh how to test it
also describe the bug you found - it should be tested firstly

**Comment by decentralauren** [comment]
@vldkhh - moved this back to QA for you to test but please hold until Lewis and I review any other potential bugs so you can test at once when ready.

**Comment by L03TJ3** [comment]
Confirmed that on celo the conversion is not done correctly, moving back to new issues

**Comment by decentralauren** [comment]
@L03TJ3 is this still relevant? If so I'll move to product backlog as it seems important / relevant to the MB release.

**Comment by L03TJ3** [comment]
@decentralauren yes still relevant. part of the current existing bugs

**Comment by vldkhh** [comment]
verified on prod

**Comment by L03TJ3** [comment]
@vldkhh should this have been closed or why did you move it back in sprint
