### ISSUE TITLE
Goodswap should use latest protocol contracts for SuperGoodDollar on CELO

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#293]
Celo will have a G$ SuperToken, and will differ slightly from other chains by having 18 decimals instead of 2
- [x] - update to latest BETA goodprotocol package
- [x] - goodswap should implement in the relevant  places the input/output components from good-design
- [x] - goodswap should use new G$ tokens format from sdk-v2

**Comment by vldkhh** [comment]
verified on prod
