### ISSUE TITLE
Goodswap should trigger FV with chainId

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#302]
- [x] sdk: modify fv sdk to also accept chainid. (it can be allowed to be empty)
- [x] ui: trigger FV with current chainid
- [x] provide chainId to the claim button at the protocol UI side

**Comment by vldkhh** [comment]
@johnsmith-gooddollar @L03TJ3 
the triggered URL has no chain included - `https://goodid-dev.vercel.app/?account=0x236A1b58aF8331A0C190403D4A20F8b42E60458a&nonce=1677597128&fvsig=0xa565b4ef46aa9aff1dea420cd2f071172d1a9a5c6024fd1efcd1c5fd0f83bef324526901540f86fe8db0e67289f3391879b0658717119f9a0f325f99194985061c&firstname=Test&sg=0xb2df753f4593bb4a9d40c6d2ac618fb309368f42b3e0d027fbcafb239f22d31c61615ffaec4c5e0711ba01598effd85ffa57c532a9707cd0b9a210977249231f1b&rdu=https%3A%2F%2Fdev.gooddapp.org%2F%23%2Fclaim`
