### ISSUE TITLE
Finalize UI claim screens

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#304]
List of UI fixes and updates according to latest screens on figma: 
- [x] - claim amount when ready for claim (only needs formatting)
- [x] #340
- [x] #341
- [x] #342
- [x] #343
- [x] #344

**Comment by johnsmith-gooddollar** [comment]
@patpedrosa Lewes tells he's awaiting for updates from Your side.
Could you provide the latest screens this week ? Thank you

**Comment by L03TJ3** [comment]
Current update is there is meeting tomorrow
and the aim for finalization is monday

**Comment by L03TJ3** [comment]
Ah! @patpedrosa I shared the specific figma screens in the designated issues
