### ISSUE TITLE
Solve issues with non-published changes in GoodWeb3-Mono for the feature branches

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#309]
For local debugging we're linking packages been updated via yalc.
But this won't work at Vercel.

My suggestion is to link such packages (e.g. good-design, sdk-v2 etc) by GitHub links if we want to deploy feature branch.
There's a service http://gitpkg.vercel.app could wrap nested package from the monorepo as it would be a single repo package
It doesn't works 'out of box' with Yarn3 but there're a few workarounds at the official github issues thread: https://github.com/EqualMa/gitpkg/issues/22

This should be tested and checked

@L03TJ3 @sirpy Maybe You may have own suggestions - let's discuss

**Comment by johnsmith-gooddollar** [comment]
if we'll use gitpkg, we may create some shell script to be run locally
it will get latest commit from monorepo and generate gitpkg urls properly encoded, then update & commit package.json

**Comment by L03TJ3** [comment]
I have just tested with a sample app
all that is needed to make a local 'yalced' package (by add or link) work in deployment is update the package.json entry from
file: > link: and update yarn.lock with this
then vercel can deploy the local package

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 please apply your solution for #297 PR

**Comment by L03TJ3** [comment]
So with my first 'mvp' attempt I failed to notice it did not resolve dependencies for yalced packages.
The steps I now have done to make it work:
1. yalc add <package>
2. do dev as usual
then before commit and deploy feature branch
3. update package.json dependency from file: <package> to link: package (file: updates yarn.lock every install)
4. yarn install
5. cd to .yalc/<package>
6. yarn link <path/to/root>
7. add yalcinstall.sh to build script (likely could be done smarter)
8. https://good-swap-qfwn61gay-gooddollarteam.vercel.app/


Then the question is if this is sufficient, or that it just would be cleaner with something like gitpkg

**Comment by sirpy** [comment]
@johnsmith-gooddollar @L03TJ3 i'm not sure I understand why do we need any of these complicated solutions
yarn and npm support installing dependencies from git based on branch/commit sha
taken from yarn docs:
`yarn add <git remote url>#<branch/commit/tag> installs a package from a remote git repository at specific git branch, git commit or git tag.`

**Comment by johnsmith-gooddollar** [comment]
@sirpy 
a) you cannot specify path in commit-based nom source, so you need gitpkg to wrap some multirepo as single repo package
b) and anyway it won't help you as you will receive **only source** while you need the package been built (with types included)

I'm thinking of releasing "dev" versions of package after each commit in PR.
to be unique version will include commit hash, the corresponding action will run at condition 'commit to PR opened'

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 I've added a simple node script `dev-release` which releases beta versions
https://github.com/GoodDollar/GoodWeb3-Mono/blob/749497a9b1d4ab60a28911092f6675ecd13bfcfb/dev-release

They're published with `beta` tag is they shouldn't be auto updated via yarn


Try to set `sdk-v2` version to `0.1.64-beta.13c3bb4` and `good-design` version to `0.0.29-beta.13c3bb4` and release ProtocolUI on Vercel

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar I would like the approach of a shell script, as I said before I don't think we need all features to be on vercel released all the time

Will test today with PR #297!

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar btw, the git commit could work
`yarn add '<package-name>@https://github.com/GoodDollar/GoodWeb3-Mono#head=<branch-name or commit>&workspace=<package-name>'`

we just have to commit dist folder on pr (remove from .gitignore)

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 I understand but it will be almost the same like commit yalc folder ;)

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 Also I've added small script at protocol ui side to apply dev version by commit hash: 
https://github.com/GoodDollar/GoodProtocolUI/pull/311/commits/3d28e243b2e7c43f6dcfe556e9b9aba2f1b62aae#diff-cec19759ed51880f81f3ca8c528fb7d6ab3514943bb61f4f14bb3b2d9b3fd363

Have set the versions from above.
