### ISSUE TITLE
Redirect the old domain "goodswap.xyz" to the new domain "gooddapp.xyz"

### ISSUE THREAD

**Issue by drptiago** [GoodDollar/GoodProtocolUI#310]
**Description**
We will change the domain used in GoodSwap.

But to make sure users who go to the old domain through any link in the old posts in social media ( AKA Twitter) find the right place is a good idea to redirect to the new domain.

**Expected Behavior**
When the user access:  goodswap.xyz automatically redirect to gooddapp.xyz

**Note**
Naturally the current system in "goodswap.xyz" must be in the new domain "gooddapp.xyz"

**Comment by johnsmith-gooddollar** [comment]
@drptiago Will you do it by yourself ? @L03TJ3 told me you're planning to do without our advice
But if you'll meet with some issues - please ask us here or in the Slack

**Comment by johnsmith-gooddollar** [comment]
@drptiago everything is fine except the redirect
the easiest way do it is to deploy and empty index.html to goodswap.xyz containing the following meta tag:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="refresh" content="0; url=https://goodddapp.org/">
    <title>GoodDollar</title>
</head>
</html>
```

**Comment by sirpy** [comment]
i've done the redireciton via cloudflare.
goodswap.xyz and gooddapp.xyz redirect to goodddapp.org

**Comment by vldkhh** [comment]
redirect works properly
