### ISSUE TITLE
Finalize Claim UX-2

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#315]
There are some left-over bugs or wonky behavior which need to be tackled

- [x] #316
- [x] #317
- [ ] https://github.com/GoodDollar/GoodDAPP/issues/3889
- [x] #318
- [x] #319

**Comment by johnsmith-gooddollar** [comment]
**FYI** - the current claim flow details

When no wallet is connected and the claim button is clicked the following flow should happen

onboard connect modal opens
after successful connect, it either:

2a. when wallet has an unsupported network or eth mainnet selected, by default it should request to switch to celo, don't switch when it already has fuse or celo selected

2b. checks for whitelist and might have to await whitelist sync
2c. if whitelist sync should happen and fails then...

3a. if not whitelisted, show fv-modal with verify uniqueness copy
3b. if whitelisted, show action modal and sends claim request
