### ISSUE TITLE
(Feature) First claim is ready screen

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#317]
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?node-id=3456%3A77073&t=kXPph0thOP5tLflF-4

Based on the figma screen after succesfull FV a modal should show with the corresponding copy that your first claim is ready
**Current Behavior**
it automatically goes to the action modal with the loader, and requests claim

**Expected Behavior** 
See screens, and discuss with @patpedrosa @SanaJamm
but initially

1. Show first claim is ready screen
2. after confirming in wallet, show loader screen
3. when tx is confirmed, show claim successful

- [x] - make sure First param is applied correctly, so that it only shows after FV
- [x] - Update Copy and content to latest screens

**Comment by johnsmith-gooddollar** [comment]
@patpedrosa @L03TJ3 This doesn't looks like a bug but the feature request.
Need to do it after #318 #319 will be fixed

**Comment by vldkhh** [comment]
verified ![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/8055abb6-3250-413b-9360-a7b236aa71cc)
