### ISSUE TITLE
- Show X when both chains are claimed on

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#318]
After a successful claim the screen updates with a new balance, and time till next claim.
it also shows a button to claim on a alternative chain

 **Current Behavior** 
The button is always shown after a successful claim, even when both chains are claimed already for the day

**Expected Behavior**
- [x] The button should be hidden when both chains are claimed on

**Comment by vldkhh** [comment]
verified ![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/eb139563-2f84-45de-a437-316c2835e0bd)
