### ISSUE TITLE
project should be deployed to different envs

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#32]
Make sure project can be deployed to different envs.
We'll start with just staging but should be easily deployed to production once it is launched
- [x] deploy project to IPFS
- [x] set domain to point to IPFS on cloudflare fi-qa.gooddollar.org for staging and fi.gooddollar.org
- [x] Verify the smart contracts addresses that are used are read from @gooddollar/goodprotocol `releases/deployment.json`
     - use NETWORK env variable
     - if NETWORK is `staging` then fuse contracts are read from the 'staging' key in the json
        - mainnet contracts are read based on the user WALLET connected network: if network is kovan read `kovan-mainnet` if ropsten then `staging-mainnet`
     -  if NETWORK is `production` then for fuse read `production` from the json and for mainnet(ethereum) read `production-mainnet`
- [x] Verify there are no hardcoded GoodDollar contracts addresses

**Comment by mukulshakya** [comment]
Looks like the initial record needs to be added manually ![image.png](https://images.zenhubusercontent.com/615acd8052594723dfe513b2/00d354a6-94d7-48fe-8399-e22d36fb4ef5)

Please add one record for the url https://dweb.link/ipfs/bafybeibf6fm2gk3khzy3uptnjacnjox5awmizkdqml6f6pufcpjystghcu

**Comment by mukulshakya** [comment]
Okay cool i’ll try again

**Comment by mukulshakya** [comment]
Okay cool i’ll try again

**Comment by MayurAdaptiveCode** [comment]
@sirpy 

Looking at the deployment.json file, we don't have staging or production defined

Can provide the contract addresses that we need to use for production and staging?
