### ISSUE TITLE
Add service worker to refresh dnslink cache

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#320]
Use this template code so user interface is always using the latest ipfs released package
https://github.com/olizilla/see-other/blob/main/see-other.js

It needs a small fix, the GATEWAY_URL is used both as an ipfs gateway and as DNS query gateway, this needs to be separated. as cloudflare-ipfs.com we use a gateway doesnt support dns queries

**Comment by johnsmith-gooddollar** [comment]
1. where it should be installed ? at protocol UI app ?
2. which GW should be used for DNS queries ?

**Comment by sirpy** [comment]
1. yes of course protocolui
2. ipfs.io
3. for the ipfs gateway we use cloudflare-ipfs.com

**Comment by sirpy** [comment]
@johnsmith-gooddollar 
please re-test.
I've added some modifications/fixes.
i've encountered an issue that for some reason it was requesting manifest.json from "cloudflare-ipfs"
so i've changed it to also rewrite requests to the ipfs gateway.
i've pushed hot fixes to master

**Comment by johnsmith-gooddollar** [comment]
@sirpy I saw a few more commits/updates
which is the status of the issue ? could it be deployed to PROD after dev/qa checks ?

**Comment by sirpy** [comment]
@johnsmith-gooddollar see my previous comment, i've asked that you retest it and explained my changes.
I have a superstrange issue that service worker is running even though REACT_APP_ENABLE_SERVICE_WORKER is not set anywhere in env.

**Comment by johnsmith-gooddollar** [comment]
@sirpy I will check
yes I saw Your comment but 2 days were gone (while we solved Android issue), You have added few more commits / fixes
So I decided to actualise status before start. Thanks for update

**Comment by johnsmith-gooddollar** [comment]
@sirpy I solved this strange issue - it was using .env.production file **always** as any build is node in NODE_ENV=production

the same issue was with Vercel - it overrode env vars set in dashboard with values from .env.production

will check other stuff next Monday

**Comment by sirpy** [comment]
the service worker doesnt seem to work as expected.
closing this in favour of regular "update notification"
