### ISSUE TITLE
Deploy testnet DAO to goerli

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#321]
Currently we dont have a dev/qa to simulate mainnet staking/protocol since ropsten was depracated
https://docs.chain.link/data-feeds/price-feeds/addresses#Goerli%20Testnet
https://docs.compound.finance/v2/#networks
https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts

- [ ] in protocol settings (fuse-mainnet, staging-mainnet) json we need to add the correct chainlink oracles addresses
- [ ]  in protocol settings (fuse-mainnet, staging-mainnet) bancor formula contract
- [ ]  in protocol settings (fuse-mainnet, staging-mainnet) compound contracts
- [ ]  in protocol settings (fuse-mainnet, staging-mainnet) donationStaking update the DAI token address
- [ ] it doesnt seem like chainlink has oracle for gas price on goerli, so we probably need to deploy a "fake" oracle
- [ ] add GoodAaveStakingV2 to deploy script
- [ ] deploy mainnet dao

**Comment by L03TJ3** [comment]
@sirpy this is not relevant anymore? besides, I would think that any 'new' staking implementation will be done in sdk-v2 from scratch anyway right?

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 goerli is shutting down
