### ISSUE TITLE
Set default chain when using claim button

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#328]
Request: If not connected, and the claim button is clicked the default chain to connect to should be Celo

**Current Behavior**
The default chain for wallet-connect is set to connectFirstChainId on the different wallet-connect modules (sdkv2/onboard). 
This takes the first chain from the list of chains in the config provided to initialization of onboard.
This is default configuration across Dapp

**Whats currently possible**
1. We request to connect a specific chain by default, and this will be the same on all the connect buttons
2. We request to switch to the desired chain after connecting

**Comment by L03TJ3** [comment]
@patpedrosa

**Comment by L03TJ3** [comment]
To implement the request, we are only able to alter how the customized wallet-connect implementation chooses which chain to connect to: https://github.com/GoodDollar/GoodWeb3-Mono/blob/588ec874a2bd366de0dc77d13e4bd0478fac8363/packages/sdk-v2/src/sdk/onboard/modules/customwalletconnect/sdk.ts#L47

So could be applied to the GoodWallet button.

We cannot add this without patch to the default wallet-connect flow

**Comment by sirpy** [comment]
Yes we have the web3 action button that asks user to switch to the relevant chain. 
So we can let user connect with walletconnect or any other wallet without asking for a specific chainid and only ask to switch when he does some action

**Comment by sirpy** [comment]
@L03TJ3 is this still relevant?

**Comment by L03TJ3** [comment]
If current behavior is what we want @patpedrosa @sirpy , then yes:
(MetaMask) 
1. not connected and clicking claim > request to switch to celo after connecting if selected network is not supported for claiming
2. if fuse is selected > claim on fuse
3. if celo is selected > claim on celo

(Wallet Connect)
1. when using goodwallet > default chain in the wallet is set to celo to connect to
2.  when using regular wallet-connect (and ie. metamask mobile) it selects current chain selected in wallet

If above is not desired, then maybe we still need to add a change somewhere

**Comment by L03TJ3** [comment]
Ok case closed then
