### ISSUE TITLE
Upgrade to react-scripts 5

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#330]
More modules decide to compile to anything from >es2019. Certain syntax is not compiled back and to make it work with webpack 4 it needs more and more plugins to be patched. Or sometimes choosing and older version of a package works as well.

**Problem**
Being blocked: #325 

Updating web3-onboard wallet-connect to use V2 implementation depends on @wallet-connect/ethereum-provider.
This compiles to ES2020, and breaks protocolUI build

**Solution**
upgrade to react-scripts@5.0.1 as at some point, we just have to

- [ ] - 
- [ ] -

**Comment by sirpy** [comment]
@L03TJ3 can you share the error and how to reproduce
i've upgraded to latest onboard packages and compiled just fine
do I need to do anything else to reproduce this?

**Comment by L03TJ3** [comment]
Install the @web3-onboard/walletconnect@next (it is an alpha package)
I don't have the error log ready here, but it is a general compile error that either breaks on nullish-coalescing or conditional chaining which is now longer compiled backward
Not exclusive to web3-onboard

it has happened with a variety of packages lately, and I got away with just choosing an older version of specific packages
