### ISSUE TITLE
force gas fee on celo

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#335]
**Bug Description**
in compliance with: https://celo.stake.id/?#/proposal/83
We should update our minimum gas wherever we specifically have set it

Currently, first bug noticed where the faucet does not give enough Celo to do an initial transaction

- [x] - Verify and/or update GoodSever sets/requests a correct gas fee
- [x] - Verify and/or update Sdk-v2 sets/requests correct gas fee
- [ ] - Verify and/or update ProtocolUI sets/requests correct gas fee

**Comment by sirpy** [comment]
@L03TJ3 server gas is fine.
does protocolui interacts with gas on celo outside the sdk-v2?

i've added a PR with forcing fixed gas price for celo and fuse.
from now on use the hook useContractFunctionWithDefaultFees

**Comment by L03TJ3** [comment]
Where is this PR you are referring to?

**Comment by sirpy** [comment]
@L03TJ3 created and connected the PR.
please review and verify that it works as expected

**Comment by L03TJ3** [comment]
@sirpy answer to question 1: only ubeswap, need to raise with them as that is by default set to 25gwei

**Comment by L03TJ3** [comment]
@sirpy additional answer to 1: also microbridge components in good-design
where it isn't working as expected: https://github.com/GoodDollar/GoodWeb3-Mono/pull/49#pullrequestreview-1309371972

**Comment by L03TJ3** [comment]
Rest of the tests on ProtocolUI were successful and does work as expected

**Comment by sirpy** [comment]
@L03TJ3 please make sure to raise the gas issue with ube
