### ISSUE TITLE
(Bug): Celo balance USD value calculation fails

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#337]
**Bug Description**
After claiming on Celo page breaks on 'Cannot Convert X to BigInt'

**Steps to Reproduce**
1. Go to dev.gooddapp.org
2. Connect wallet with Celo Chain
3. Claim UBI
4. After confirmation, or returning to the page it breaks

**Expected Behavior**
Should show G$ balance + USD value

**Additional Context**
https://github.com/GoodDollar/GoodWeb3-Mono/blob/6408d1960dfa382c89b7344dff7cd4d4a9c2dda0/packages/good-design/src/core/layout/BalanceGD.tsx#L36 
(Above is where it breaks)

![image](https://user-images.githubusercontent.com/6606028/220200462-51ee77be-eae2-4d1f-a378-f515932aa3d9.png)

**Comment by sirpy** [comment]
what type is gdPrice?
it seems like amount is < 1 and gdPrice is BigInt/BigNumber, so to perform
multiply it needs to convert amount also to BigInt which can not be done
for fractions.
the solution seems to me to first convert gdPrice to number and then
multiply
secondly it seems the amount in the ubipool is very low if it gives away <
1, you can use the dev account mnemonic "season..." to mint G$s to the
UBIPool contracts

**Comment by L03TJ3** [comment]
Solution has been rejected, calculation should be done with bignumbers, and no formatting until final render
