### ISSUE TITLE
User should be able to use gas faucet on gooddapp

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#339]
- Currently the faucet on gooddapp will request topping from goodserver if his balance < 250000 gas units.
This will work ok for new accounts.
- Some transactions like claiming might require more than 250k gas, so if user has just a little over 250k but under the gas required for claiming he will not be able to claim and it will need request goodserver for gas.

- On the wallet since everything happens on the background, we check before each TX if user has enough gas, if not the user will issue a TX to request gas from the Faucet contract, only in case he doesnt have enough gas to make the request to the Faucet contract then it will request goodserver.

- For gooddapp since the user has to sign every tx we need to decide on the Faucet flow, or even remove it.
- Reason for removing it the Faucet contract needs constant funding, currently estimated at 3.5K$ a year for 50K users
 
Possible faucet flows:
1. A top wallet button flow -> once user presses it, it will either invoke a TX to faucet or request to backend
2. Background flow -> once user balance reaches a threshold -> show modal asking if user wants to issue a tx to top wallet -> follow top wallet button logic
3. check gas required before each tx  flow -> and then show modal like in background flow
4. Alternate background/top wallet button flow -> create a tx to swap G$ to Celo/Fuse

I'm in favor of 4. with a topwallet button/buy gas button the cost for 1M units of gas would be around 20G$ on celo and 4G$ on Fuse

**Comment by sirpy** [comment]
@L03TJ3 @johnsmith-gooddollar @patpedrosa 
review, ask questions, and comment please

**Comment by L03TJ3** [comment]
1. I think part of the solution is to find ways to have users learn for themselves and help educate them how to make sure there are enough funds for gas fees, we cannot forever keep holding their hands, and having a faucet is definitely not scalable (Maybe we can flag new users for a certain period of time, IE. first two months after being whitelisted, you are eligible to use the faucet)
2. Like done on testnets, have the faucet only be used once every x hours
3. Definitely think it should only be for at least whitelisted wallets (now it runs for every wallet connected)

All of the above are to minimize the use and need of the faucet and bring down the costs of funding it.

Then I too think, if we don't rely on users to swap themselves, that flow 4 could be possible, however small caveat I think to spot:
Where a daily claim of G$ on FUSE translates to 0.1 FUSE = around 100 claims so someone is taken care of for the next 3 months of claiming (not considering other transactions done with wallet)

On Celo, a daily claim of G$ translates to 0.01 CELO = exactly the cost of the claim transaction
(Or is the amount of G$'s claimable different on both chains?) if yes, it translates to roughly the same

Then I think a single swap will relieve a lot of users for a good amount of time to having a need of the faucet

**Comment by L03TJ3** [comment]
But by all means, and I think I have mentioned it before. The faucet should definitely not run automatically for everyone without any rules or checks applied

**Comment by sirpy** [comment]
The question is not about the rules and checks of the faucet it is about
the user flow/UX.
It doesnt cost 0.01 celo to claim, it should normally be around 0.0015 to
claim. celo txs would be 5 times more expensive in $ terms at current
market prices.

**Comment by sirpy** [comment]
@patpedrosa the question is not wether we should have a faucet or not but about the UX flow, how should it it be implemented. With the main problem is that users potentially need to sign a TX.

The initial topping of gas to new accounts is currently working.
The question is subsequent toppings. If we do rather than the user it is more load on our servers, more gas we need to pay and makes gooddapp reliant on us to function properly.
