### ISSUE TITLE
User should be able to go to fuse bridge

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#34]
GIVEN a user
WHEN the user clicks on the fuse bridge button
THEN  the user will be redirected to https://app.fuse.fi/#/bridge

Acceptance Criteria
The button should appear on the left bar
The button should look the same as the link to the wallet.
The button will redirect the user to https://app.fuse.fi/#/bridge

**Comment by MayurAdaptiveCode** [comment]
@sirpy 

![image.png](https://images.zenhubusercontent.com/61559a3f6f288803279d3515/230289fd-290c-4281-99f8-2ba8f94c3515)
