### ISSUE TITLE
- update modal copy's/content

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#344]
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?node-id=3471%3A76712&t=kXPph0thOP5tLflF-4

This applies to verify uniqueness / action modal. Skip the FirstClaim/AfterClaim screens for this one

- [x] - update copies
- [x] - add images

**Comment by vldkhh** [comment]
[Uploading... image.png]
