### ISSUE TITLE
- show switch chain modal when using the NetworkModal for switch

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#353]
**Bug Description**
Currently when user is connected with wallet-connect and clicks on switch chain, nothing shows on desktop to indicate what is happening or what the user should be doing
on mobile, the popup to select wallet shows.

We just need to add a general modal indicating to confirm for switch chain 

**Steps to Reproduce (desktop) **
1. Go to dev.goodapp.org (switch network fix has not been released yet)
2. Click on connect wallet
3.  click on current network (top-bar)
4. select a chain to switch to
5. nothing shows, even tho the request has popped-up in wallet

**Expected Behavior**
A modal should be shown indicating that a user should go to its wallet

**Comment by vldkhh** [comment]
attachments: 
https://images.zenhubusercontent.com/348622803/53577356-e668-4afc-86a7-c648472fb02c/558543d1_8df2_4711_86aa_8e232b1e7435.mp4


at least show something like that:

![Snag_4d8b8997.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/ac3a1184-e344-41d2-86bd-7c9b586b3965)
