### ISSUE TITLE
[BUG] Metamask triggered an action popup every time then you are on the claim page 

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodProtocolUI#357]
Metamask triggered an action popup every time then you are on the claim page 
It shows after claim on both chains

Steps:
1. Connect to Metamask
2. Claim on fuse and celo chains
3. Go to the Swap page 
4. Go to the Claim page

Actual: the metamask popup shown with claiming info 

https://images.zenhubusercontent.com/348622803/9ea7f86a-4c8c-4207-a243-985af75a1223/3efd49b4_c9eb_47c2_bd51_3cfefacd49f7.mp4

**Comment by vldkhh** [comment]
The same bug with google after claim both chains

**Comment by L03TJ3** [comment]
Issue is after doing FV (see image URL)
We never remove the verified param (which is what triggers a claim request)
