### ISSUE TITLE
Approval of "spend token" should always be set on inifinity 

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#36]
Before buying/ selling/staking a token, there's a need to approve the token.

all approval processes should be set on infinity so the user will need to go through the approval process only once. 

Given user that wants to stake, swap or perform any other transaction that requires token approve
When user is shown the transaction to sign the token `approve`
Then transaction approve amount should be set to Max(uint256)

**Comment by sirpy** [comment]
@tomerGD what do you mean?
do you mean that approve should happen one time with an infinite value? so for the same token there's no need to approve again?

**Comment by adaptivecodeio** [comment]
Conduct further refinement.

**Comment by sirpy** [comment]
i've moved the issue to icebox

**Comment by imanshu03** [comment]
@sepu85 please take a look at this document for the blocker we are facing while trying to achieve this functionality https://www.notion.so/Ticket-36-Blocker-558e57d5765d407b92c8e136544df4f2

**Comment by sepu85** [comment]
@imanshu03 please share access to gustavo@gooddollar.org

**Comment by sirpy** [comment]
@imanshu03 @adaptivecodeio  when reporting issue use github we dont need any more services unless there's a specific need.
if you need to attach video use some video sharing service.

**Comment by adaptivecodeio** [comment]
Access shared

**Comment by imanshu03** [comment]
When user approves for first time with spend limit amount set to Max(uint256) value for the first transaction and afterwards when we try to sell again for second time or forth, we have to approve the transaction again as the applications current functionality is built in a way to approve each transaction. We need to further refine this approach as implementing infinity spend token approval would require a major change in application flow. @adaptivecodeio @sirpy @sepu85

**Comment by sirpy** [comment]
@imanshu03 that's ok.
in my PR i've changed it to check the approval state, if there's enough approved pressing approve will happen immediately without sending a TX.
copy paste this check to other places where the approve button is shown.
we can find a solution to remove the approve step in a different issue

**Comment by imanshu03** [comment]
@sirpy Please review PR - https://github.com/GoodDollar/GoodProtocolUI/pull/101
I have made the changes for Buying and Selling as you did for Staking
