### ISSUE TITLE
Bug: balance loads too slow after succesfull claiming

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#360]
**Bug Description**
After claiming it can take some seconds for the balance to update

**Steps to Reproduce**
1. Go to gooddapp
2. Connect wallet
3. Claim on a network
4. After confirmation of transaction, see how long it takes for balance to updated

**Expected Behavior**
Either show that a loader to indicate its pending blockchain update (like we do in side-bar wallet balance)
Or??? <suggestions here>

**Additional Context**
![image](https://user-images.githubusercontent.com/6606028/222777152-10ee5549-f7d1-441a-a27f-c5b69fbbb152.png)

**Comment by sirpy** [comment]
@vldkhh lets retest this

**Comment by L03TJ3** [comment]
@vldkhh on dev btw! I made some changes which might have made it load faster
