### ISSUE TITLE
(Bug) New TX issues with claim on the wallet app

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#362]
![image.png](https://images.zenhubusercontent.com/6135d0416eed5f7809f4ee6b/0e1c5dc4-8e5d-42f0-a6fe-b91cd3f64538)

**Comment by sirpy** [comment]
@johnsmith-gooddollar 
this is just 40-60 events with 12-20 users. it doesnt seem like something we can fix, looks like unpredictable blockchain error
