### ISSUE TITLE
GoodStaking  And Protfolio broken

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#367]
The mainnet staking view is broken and doesnt show anything
Portfolio also seems broken and doesn't show your staking on fuse

- [x] seems like we are using a bad infura api endpoint (ie not our api key), need to configure release with our own infura api or with public cloudflare-eth rpc
- [x] there's a ApoloIndex error

![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/414f6902-348a-4883-9807-d3ccf6a10877)

**Comment by L03TJ3** [comment]
Gooddapp has been added to whitelist on fallback-api
just have to verify if we want to move this fallback to a different one
