### ISSUE TITLE
Bug/Feature: Verify uniqueness and sign second message

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#368]
**Bug or Feature Description**
On mobile (both browser and wallet app) when a user clicks the claim button and is not whitelisted, it shows you a verify uniqueness modal + description what is happening.
When clicking verify-I-am-human in this modal, either a native pop-up shows to select an app/wallet to open with, or it auto switches to the connected wallet app to sign the first request.
signing this message switches the user back to good-dapp.

**Current behavior**
The modal to sign a message in the wallet still shows, but this could be confusing if a user has not properly read or understood the description on the first modal that it needs to sign twice. No indication of a second signing wallet is shown in this stage, and a user would only be able to know by switching back.

**Expected Behavior**
options:
a. update copy that indicates more directly that there is a second message to sign
b. could be a bug that the second request is not also asking to open/go-to wallet
c. **suggestions here**

**Comment by sirpy** [comment]
only one signature is required. see my sdk-fixes PR
