### ISSUE TITLE
User should connect to correct network

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#37]
A user might not be on the correct network when he performs and action or might not have the "Fuse" blockchain available on his wallet.

- [ ] **Examine how Sushiswap is handling (examine UI and Code) network switches in these two cases**
    - **user connected to a non supported network by sushiswap**
    - **user select to switch a network**

**valid networks:
staging env - kovan, ropsten, fuse
production - mainnet, fuse**

Given a user that connected his wallet
When 
- [ ] case a: he is connected to a wrong network (non ethereum/fuse)
- [ ] case b: he switches to or selects fuse network (in network selection)
- [ ] case c: he tries to perform an action on the wrong network (ie tries to "Claim" when network is ethereum or tries to stake when network is fuse)

Then
- Show dialog and close it once network change to the correct network is detected
**in case user is using metamask**
- case a: user should be shown a select network dialog
- case b:
    - if user doesnt have fuse RPC defined, perform request to add network
    - perform request to switch network
- case c: perform request to switch network

**other wallets**
- show dialog and ask user to switch to a supported network. close dialog once network switch is detected.

**Comment by sirpy** [comment]
@MayurAdaptiveCode the ticket description is correct.
regarding case c, verify what's the behavior today, I think for example the claim button according to the specs and design, should show a popover saying it can only be done on fuse. so that's good enough behavior.

**Comment by imanshu03** [comment]
PR - https://github.com/GoodDollar/GoodProtocolUI/pull/66

**Comment by sirpy** [comment]
@imanshu03 @womaninblockchain 
this needs to be tested with walletconnect how does it behave when user isnt using metamask?
specifically you are hardcoded using the window ethereum and not the active web3 library user chose to connect with, which could be wallet connect

**Comment by imanshu03** [comment]
@sirpy We were getting errors while using the active web3 library for switch network on "connected to wrong network" scenario, that is why I used window ethereum to switch networks

**Comment by sirpy** [comment]
@imanshu03 yes that's because the reactweb3 has a "supported chains" list and if you start from an unsupported chain it will not work.
in any case if something is not working, you need to understand why, not simply change the whole architecture without understanding the implications.

**Comment by imanshu03** [comment]
@sirpy I had gone through enough links to find the issue caused due to the active web3 library and its fix but was not able to find one that is why I changed to window ethereum. But I'll be more careful next time when doing any such thing and clarify it before respectively.
