### ISSUE TITLE
Fix in the Claim and Swap analytics events

### ISSUE THREAD

**Issue by drptiago** [GoodDollar/GoodProtocolUI#376]
Is related to [268](https://github.com/GoodDollar/GoodProtocolUI/issues/268)

**The Claim events ( claim_start and claim_success) are not sent anymore to the data layer**
( line 6 and 7 of the sheets)

**In the Swap events (swap_start and swap_success) when performing a SELL operation the property type says "buy"**
The correct is `{type: "sell"}`
( line 42 and 44 of the sheets)

```
{action: "swap_start",
 user: {id: "0x703550294eDD3E1A700f3F0D2347b037BC6A0030"},
 type: "buy",   <--------------This type must to be "sell"
 network: "FUSE",
 amount: "5000",
 tokens: ["G$", "FUSE"]
 }
```

**In swap_confirm when performing a SELL operation the event is triggered twice.**
(line 43 of the sheets)

**All the events are in the sheets in the color Yellow with details in the column E**
The color red are future improvements.
https://docs.google.com/spreadsheets/d/1nTiU5h2XtsGhJ8Vi0USn-B5jnUSMWs5OEhjwPfatthA/edit#gid=1010408646

**Comment by L03TJ3** [comment]
Confirmed above got resolved
