### ISSUE TITLE
faucet doesn't seem to work after user claims

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#382]
on dev env
connect a wallet with no funds
get first top-up
do  claim
doesn't top-up again (claim tx leaves to less native-funds)

**Comment by L03TJ3** [comment]
from @vlad
https://app.birdeatsbug.com/workspaces/7ce1bd50-c755-4b2d-89b8-62a480984405/collections/9eb28a35-c222-40de-9b13-1c0bc46f9731/sessions/c2vpS154NHIs8srdEQdY7HmbkCQ1KYnyZm7vlGPrqm-g

**Comment by sirpy** [comment]
issue was found at the backend and was hotfixed
