### ISSUE TITLE
Failed to resolve ENS name/ Failed fetching token list

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#385]
**Bug Description**
Upon initial loading of gooddapp, or not being connected to mainnet the console is filled with warnings/errors about
not being able to resolve ens names, and not being able to fetch lists

It doesn't seem to break anything, but also it seems to be ran before its ?necessary?

1. - [x] - What is used for, do we still need it?
2. - [ ] - if yes, make it only run after library is initialized.
3. - [ ] - if yes, Look if there are actual deprecated lists (hard to tell, some warnings might just be delayed promises)

**Steps to Reproduce**
1. Go to gooddapp
2. open console

alternative
1. go to gooddapp
2. connect a wallet (non-mainnet)
3. open console

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar @sirpy As far as my understanding went this is actually leftover logic that we don't need or use

I believe the intended use case for it is to have customization options for which token lists to show/not show
(as is possible on uniswap/sushi swap etc)

Since we don't offer this feature, likely this whole updater flow can just be removed

**Comment by sirpy** [comment]
What about the tokenlist for swapping from reserve.. not related?
so lets try to disable that logic

**Comment by L03TJ3** [comment]
No not related, just re-checked and we use getTokenList from sdk-v1, not the getTokenList from UI

**Comment by vldkhh** [comment]
Verified on QA/Prod
