### ISSUE TITLE
Show modal with error/success for kima bridge

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#389]
Currently when you submit the bridge transfer there's no feedback to user.

- [x] feedback on success, i couldnt test what happens on success. if the screen changes then nothing to do here
- [x] feedback on failure. show modal with error message.

**Comment by vldkhh** [comment]
@L03TJ3 how to trigger the error modal?

**Comment by decentralauren** [comment]
@sirpy can we close this as kima is no longer relevant?
