### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'navigate')

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodProtocolUI#396]
[BUG] Cannot read properties of undefined (reading 'navigate')

There is no navigation back to the app after passing the FV on dev.gooddapp.org:
https://app.birdeatsbug.com/sessions/hFJ88ivqSCQbp-ZBqXfkj5Zxg84e7DqJ4f54e9X3t22s?consolePane=75&seekSeconds=64.862

Steps:
1. connect the wallet 
2. click on the claim button
3. pass the FV
4. observe the result

Actual result:
The app is stuck on the FV page

Expected result:
The app should be navigated back to dev.gooddapp.org

**Comment by sirpy** [comment]
@vldkhh as in the past, please follow our format of specifying which envs are effected or not. is this a dev env only issue?

**Comment by johnsmith-gooddollar** [comment]
hot fixed, pushed to the all branches https://github.com/GoodDollar/GoodDAPP/commit/b171aa5995b68db51af26031a23d7af29e34314e
