### ISSUE TITLE
Send walletconnect missing peerid event to analytics

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#397]
for G$ walletconnect
- [x] on new connection made if peerid is missing send an WALLETCONNECT_FAILED event
- [x] on new connection made if peerid is not missing send an WALLETCONNECT_SUCCESS event

**Comment by drptiago** [comment]
I didn't find theses events in Amplitude neither in Google Analytics

**Comment by L03TJ3** [comment]
@drptiago could you recheck with these events:
wallet_connect_failed
wallet_connect_success

**Comment by drptiago** [comment]
Yes, I successfully find the events in Good Dapp Google Analytics.
https://analytics.google.com/analytics/web/#/p300354113/reports/intelligenthome
