### ISSUE TITLE
Add event for celo/ubeswap component

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#398]
- Try to use usedapp notifications to be updated of new tx waiting for signing and tx complete
- See if from the notificaiton you can identifity that it is a call to the ubeswap router

- [ ] swap start
- [ ] swap end

**Comment by L03TJ3** [comment]
@sirpy This won't work as usedapp transactions keep only track of transactions send by useContractFunction calls

**Comment by L03TJ3** [comment]
Since moving to uniswap widget we now have events implemented, so closing
