### ISSUE TITLE
User should be able to connect with his G$ wallet

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#4]
we have a few options
1. just give instructions how to export wallet to metamask (secure, complicated for user, easy to implement)
~implement torus login flow as we have in wallet (less secure, easy for user, medium to implement)~
~implement wallet connect api in G$ wallet. (secure, medium for user, hard to implement)~

- [ ] show link to instructions https://help.gooddollar.org/kb/user-guides/how-to-connect-g$-address-to-metamask
- [ ] should be part of the first user onboarding experience
- [ ] decide where and how to display instructions (Tomer)

**Comment by sirpy** [comment]
@Esfir-E @tomerGD need your thoughts on this

**Comment by tomerGD** [comment]
I have no idea what does this ticket means to be honest, please explain 

@sirpy ?
@Esfir-E ?

**Comment by sirpy** [comment]
@tomerGD a user need to use his G$ account in the protocol UI

**Comment by thaddaeusus** [comment]
> what does this ticket means

Ticket just about:

1. Discuss&decision how we connect user's wallet to protocol (see pt. 1-3), and
2. Implementation of picked decision.

As I understand after calls we decide to pick way 1 (export to metamask and connect mm) for now. @sirpy am I right?

**Comment by sirpy** [comment]
@tomerGD you first need to
1. put instructions link in issue
2. design where how and when to show instructions
