### ISSUE TITLE
User should see his Social Contribution on the Portfolio page

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#40]
How much G$s in UBI did the user help to generate from staking and simply holding g$s

**Comment by tomerGD** [comment]
@sirpy https://docs.google.com/document/d/1lCbaATypXBci1zXEncjyJhPyg_E3ZAEspDe9AInaBlM/edit#

Need your help aligning that

**Comment by adaptivecodeio** [comment]
@sirpy 

Can you verify the apy calculation is correct?

**Comment by sepu85** [comment]
@adaptivecodeio Social APY is `Third party Protocol APY / Reserve Ratio` if third party APY (e.g. compund on DAI) is 3% and reserve ratio is 85%, then Social APY is 3 / 0.85 = 3.53%

**Comment by sepu85** [comment]
what do you expect from me here @sirpy ? I think my last response clarified this already.

**Comment by sirpy** [comment]
this is not about the protocol.
this is about the social apy that appears at the user portfolio page.
it is actually not APY but rather nominal according to tomer's request, ie how many G$s in total did the user help to create.
please read Tomer's doc.
