### ISSUE TITLE
[Bridge] Tokeninput component should use bignumbers/currencyvalue

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#400]
Currently it just users numbers and multiplys by 10^decimals which can break for 18 decimals

**Comment by L03TJ3** [comment]
@decentralauren Assigned you.
this is part of the remaining fixes that would have to be done if we decide on enabling the microbridge on gooddapp

But that obviously still has to be discussed properly. also @sirpy when/if/how we consider this to be done (because gd-wallet2 migration)

**Comment by decentralauren** [comment]
@sirpy:

* Has this been built / has work been done?
* Is this the same thing we are asking to complete in the last 2 checkboxes of [ticket 289?](https://github.com/GoodDollar/GoodProtocolUI/issues/289). If so, can we close this ticket to avoid dupes?
