### ISSUE TITLE
[BUG] The Claim flow doesn't work properly on DEV env

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodProtocolUI#401]
The Claim flow doesn't work properly on DEV env

Steps:

1. Create a new wallet via MM
2. Connect the new wallet to the app
3. Wait until your wallet will be topped up
4. Perform FV on this new wallet
5. After redirection back from FV - observe the result

Actual result:
The MM tx request goes up in counts (could be more than ~200 requests). The 'Claim is ready' popup starts to blink time by time. Unable to do a claim during these events

Expected result:
There are no such issues after FV

Env:
DEV env - https://dev.gooddapp.org/

Attachments:
https://app.birdeatsbug.com/sessions/HDWFiCKpl2V-NJTRblU9Si0IN4gg5-KHEvpSGGA07-r6?consolePane=true
https://images.zenhubusercontent.com/348622803/4e27e90d-74af-43d5-b83e-e90bc1623c38/5b01d4dd_5d7f_446e_a355_fff4c9ffdccc.mp4
https://images.zenhubusercontent.com/348622803/a1e671be-3890-4123-b8d9-945d08ad819f/32d9f822_a2d9_45c7_8473_7423eaf56c80.mp4

vldkhh

**Comment by L03TJ3** [comment]
fixed here 05242473bdd20a717ea1926aca60b76591897a65

awaiting release
