### ISSUE TITLE
Add onetime payments to contracts

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#408]
@sirpy added OneTimePaymentsV2
the goodprotocol package @johnsmith-gooddollar, it should have it for all dev/staging envs. i've also added 'development-goerli' env.

1. to deposit eth you need to call on the contract `depositAsset(paymentId,asset = 0x0..00 for eth, amount)
2. need to listen to new events from this contract like we do for OneTimePaymentsV2. the events are almost the same, they also have now an added "asset" field at the end

**Comment by sirpy** [comment]
@johnsmith-gooddollar add issues on wallet not protocolui
