### ISSUE TITLE
[BUG] The balance and tx card are not updated livetime on the Android App

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodProtocolUI#411]
The balance and tx card are not updated livetime on the Android App

Preconditions:
1. The latest staging Android app is installed
2. Two accounts available

Steps:
1. Create a tx between two accounts (from web/desktop to the Android app)
2. Confirm tx
3. Pay attention to the Android app (balance and card tx)

Actual result:
The balance and card tx are not updated livetime, only after closing the app and open app again 

Expected result:
The balance and card tx updates livetime without closing the app

Env: 
Staging 1.51.1-3
Version 1.51.1-3 (4073)

Attachments: 
https://images.zenhubusercontent.com/348622803/31585d6e-7951-494f-a23f-9a077d474282/ba80fe86_c9e0_4dae_9678_10528cc03f83.mp4

[https://app.zenhub.com/files/348622803/209aa246-e434-492f-8705-fc7c2eea04eb/download](https://app.zenhub.com/files/348622803/209aa246-e434-492f-8705-fc7c2eea04eb/download)

**Comment by sirpy** [comment]
@vldkhh is this should be on GoodDAPP repo?
@johnsmith-gooddollar can you also look at this issue?

**Comment by johnsmith-gooddollar** [comment]
@vldkhh why this was closed ?
