### ISSUE TITLE
Show Celo/Fuse chainID and RPC at the ExportWallet screen

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodProtocolUI#415]
I've fixed url, now it shows the first one RPC from the list.
The data displayed depends on the current network been selected (e.g. for fuse it shows FUSE's RPCs/networkid, for CELO - the corresponding data).
So I've removed "FUSE" word from the labels, now it's just "Network RPC URL" and "Chain ID"

- [ ] add current network name to the labels (e.g. FUSE/CELO chain ID , FUSE/CELO RTC URL) ?
- [ ] show rpc.fuse.io for FUSE, forno.celo.org for CELO

**Comment by L03TJ3** [comment]
moved to gooddapp: https://github.com/GoodDollar/GoodDAPP/issues/3981
