### ISSUE TITLE
Add bubbles while overing on all titles of the portfolio 

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#42]
- [ ] add info bubbles over portfolio table titles
- [ ] put a place holder for the text + il8n

**Comment by mukulshakya** [comment]
Hey @tomerGD 

can you share a design mockup for the task?

**Comment by sirpy** [comment]
@mukulshakya @MayurAdaptiveCode 
here's the figma link to the current design
you can see the tooltip in multiple places. there should be a `?` or `i` icon next to the title and on hover it show show the tooltip.
@tomerGD we need a ?/i icon? or just show tooltip on title hover?

example form the design
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/43b2170d-ba0a-4b3f-b144-c92da551959a)

**Comment by mukulshakya** [comment]
Thank you @sirpy 

Hi @sirpy @tomerGD This is the current design of the portfolio page and `?` is placed in some places also. Where additionally is it needs to be added?

 ![image.png](https://images.zenhubusercontent.com/615acd8052594723dfe513b2/b530255d-95bf-4500-bb87-af61bbe93a35)

**Comment by tomerGD** [comment]
@mukulshakya use exactly the same deisgn as TOKEN and PROTOCOL has, please ad it to 
TYPE, STAKE, G$ REWARDS, MULTIPLIER, GDAO REWARDS

**Comment by sirpy** [comment]
@mukulshakya I suggest that we do dynamic
if the text translation key for the title is non empty then show the `?` icon. ie `if(iln8('token_explanation')!="")`

**Comment by mukulshakya** [comment]
Hey @tomerGD @sirpy 

Can i get the all the messages that we need to show on the bubble.

**Comment by mukulshakya** [comment]
PR - https://github.com/GoodDollar/GoodProtocolUI/pull/58

**Comment by mukulshakya** [comment]
Bubble have been added to the portfolio table we just need text description for each one
- Type
- Stakes
- G$ rewards
- Multiplier
- GDAO rewards

![image.png](https://images.zenhubusercontent.com/615acd8052594723dfe513b2/6c8880f9-1b28-4d01-b25c-f844e45a63ff)

**Comment by adaptivecodeio** [comment]
@tomerGD 

Can you provide the text description for the bubbles please, thanks.

**Comment by sirpy** [comment]
@adaptivecodeio there's an with a document with the texts

**Comment by mukulshakya** [comment]
Hi, @sirpy which document is this, can you link that here? Thanks

**Comment by mukulshakya** [comment]
I found the doc but the text is missing for the headers:
- Stakes
- G$ Rewards![image.png](https://images.zenhubusercontent.com/615acd8052594723dfe513b2/a27ee3e1-9541-455a-b869-b1420a4dc1b4)

**Comment by sirpy** [comment]
@sepu85 
Hey Gus, can you take this over?

**Comment by sepu85** [comment]
@mukulshakya sorry for the delay in this, here the input you are requesting:

* Type:
Staking could be of two types: UBI for funds staked on the GoodDollar trust for the generation of new G$ for universal income distribution, or Governance (to be enabled) for staking G$s for GOOD Rewards. (see issue #67 )
* Stakes
Total amount on value staked 
* G$ rewards
How much value your stake has accumulated so far
* Multiplier
*This is already set, keep current text*
* GoodDAO rewards (please change to GoodDAO rewards as siggested in issue #67 )
How many GOOD tokens you are accumulating by this stake position.
