### ISSUE TITLE
Bug: wc2 does not emit disconnect/switch event back from dapp

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#420]
**Bug Description**
There is no need for the approval of switching chains as a wallet can now be easily switched between multiple supported chains
However, there supposedly should be an event emitted: session_event
which can be tracked by a connected wallet and update connect chain details etc

I am not sure where the issue lies.
at least to me, it seems with our wallet that the events are properly listened for.
At first glance, it looks like it just never gets emitted from gooddapp

Anyway need to require a bit more research as to where this goes wrong, and why the connected wallet is not pinged with updates from the dapp when switching chains. Could be an issue on either side

- [x] #421

**Steps to Reproduce**
1. Go to dev.gooddapp
2. Click on connect wallet + click on gooddollar button
3. dev.goodollar opens > click on connect
4. try switching in wallet > chain details update, the dapp is updated
5. go back to dapp > switch chain > dapp updates > no response to any event in wallet

**Expected Behavior**
Potential wallet-fix 
- [ ] - We just update chain details in UI whenever a request is made on a different chain than the details we currently have cached
- [x] - Disconnect has the same issue as above

**Additional Context**
It is not a 'breaking' bug, and the user can still continue using either wallet/dapp. After switching the tx requests are sent based on the dapp's current active chain and are received as expected. The request itself contains the active chain details.

**Comment by sirpy** [comment]
1. This doesnt seem like an issue as WC2 sends required chain with each TX.
2. How are other wallets/dapps behaving? WC2 reference demo wallet and dapp? other wallets/dapps that dont use onboard?

**Comment by L03TJ3** [comment]
1. see the last checkbox. is that is your proposed way to tackle it? always base active chain on the last incoming request?

it's all just about having the UI properly reflect back to the user what the current state is, that's all.

**Comment by L03TJ3** [comment]
not going to fix
