### ISSUE TITLE
Bug: swap to receive amount keeps calculating

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#423]
**Bug Description**
When swapping G$ > X, the amount to receive shows up 1 time, and then keeps calculating
it appears to only happen on the selling of G$

**Steps to Reproduce**
1. Go to gooddapp
2. connect wallet and switch to either fuse / mainnet
3. Set gooddollar for sale
4. fill in amount, see receive input
   b. also happens when you type in the receive input first

**Expected Behavior**
After calculation is done it should not update every 1 milisecond

**Comment by vldkhh** [comment]
verified on prod
