### ISSUE TITLE
Bug: (wc2) Sending transactions on celo do not contain appropriate tx details

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#424]
**Bug Description**
Not all details are provided in the payload for tx handling (when using wallet-connect / onboard / gooddollar-wallet)
As seen in screen (an approve tx) has value 0, so you give permission for 0 G$ to be spend

Need to determine if this is wallet-connect or ubeswap component issue

- [ ] - approve requests don't hold value
- [ ] - a swap requests gives a not-enough balance (maybe a wallet-fix needed)

**Steps to Reproduce**
1. Go to gooddapp
2. connect gooddollar wallet, and try to swap (celo/ubeswap)
3. see the transaction detail modal popping up in wallet

**Expected Behavior**
Values should be properly set and send as payload.
Approval should be done for the amount trying to be swapped. 

**Additional Context**
![image](https://github.com/GoodDollar/GoodProtocolUI/assets/6606028/04e59ae2-5737-471a-850a-9cc92e818b82)

**Comment by sirpy** [comment]
@L03TJ3 this is not a bug, "value" is for sending native tokens with the TX.
The specific function call and its data are encoded in the "data" field
you can try to be the data here and see it decoded:
https://www.moesif.com/solidity-abi-hex-decoder/decode
