### ISSUE TITLE
Change github action to deploy to vercel and not IPFS

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#425]
- Don't see any advantage in using IPFS as anyways gooddapp is served through our domains. (country.one might be a future decentralized domain)
- Cloudflare domains forces us to use their IPFS gateway which has considerable costs while vercel is free 
- See https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
- deploying to vercel from github actions would save us build time on vercel as we have just 1 concurrent job there
 
- [x] setup github actions to deploy to vercel
- [x] configure vercel with gooddapp.org and gooddapp.xyz domains

**Comment by L03TJ3** [comment]
@sirpy @johnsmith-gooddollar 
I noticed this item from the backlog (while I was a bit confused where to add a new secret for protocolUI)

We already run everything on vercel now..
is this one a task we want to push forward soon?

**Comment by sirpy** [comment]
@L03TJ3 it is not high priority. you already implemented similar flow for goodcollective so i'm not sure why the confusion.
you can probably test it quickly by duplicating the goodcollective script for protocolui and set it to run only for a specific branch

**Comment by L03TJ3** [comment]
Will be released to vercel now, fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/fe247657a62d9a60a30060a37b1e678944462843 / https://github.com/GoodDollar/GoodProtocolUI/commit/fad073dd5b61e629d579566619ff3c7c2c9b803d

Only need to configure the domains correctly for dev/qa/prod

**Comment by L03TJ3** [comment]
deployed and in production
