### ISSUE TITLE
[BUG] Redirect to the wallet.gooddollar insted of FV standalove after clicking on the Claim button 

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodProtocolUI#429]
Reproduced on QA env. 

Steps (for a non-whitelisted wallet):
1) open the qa.gooddapp
2) click on the connectwallet
3) choose connect via Gooddollar Wallet
4) click on the claim button (gooddapp side) after connection
5) observe the result 

Actual:
Opens the wallet.gooddollar (prod env insted on QA and no standalone app)

Expected:
Opens the FV standalone app

ENV: qa.gooddapp, qa.gooddollar

Attachments: 
https://app.birdeatsbug.com/sessions/Qg0pp8PFny8kAM6G6SV7Tkyx1wtjDEpqbtgz9-EbYvhD?consolePaneHiddenGroups=Click%26Keystroke%26Error%26Assertion%26Network+Error%26Blocked+Request%26videoStart%26videoPause%26videoResume%26videoStop%26screenshot%26Instant+Replay%26Dir%26Group%26Table%26Count%26Profile%26Time%26Trace

**Comment by L03TJ3** [comment]
@vldkhh lets sync later as I am unable to reproduce and works here as intended (clicking verify just pops-up on the qa.gooddollar wallet)
