### ISSUE TITLE
Bug: doing any TX while on a wc2 connection opens metamask page

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#431]
**Bug Description**
User is navigated from gooddapp to the download page for metamask whenever doing any tx while using wallet-connectv2

**Steps to Reproduce** (taken from thread on onboard issue)
1. use onboard connect modal (latest)
2. click on wallet-connect (v2)
3. click on one of the shown deeplink-wallets
4. DONT CONNECT
5. click back, and use QR scanning or copy URI to connect an alternative wallet
6. nce connected, attempt to do a transaction
7. redirect happens on dapp
*. can verify here that the page that opens is the link set in storage on walletconnect_deeplink_choice

**Expected Behavior**
This should not happen
- [x] - remove all wallets from desktop list which don't have a desktop app

**Additional context**
As described in below 3rd party threads, the issue lies with the local storage item walletconnect_deeplink_choice
this never gets cleared properly and can be mismatched with an actual wallet being connected causing an incorrect redirect to a deeplink uri

**Comment by L03TJ3** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/issues/2303
wallet-connect issue thread

open one on web3-onboard: https://github.com/blocknative/web3-onboard/issues/1780
since the behavior with the modal used on wc2 demo app is different then when using onboard

**Comment by L03TJ3** [comment]
https://github.com/GoodDollar/GoodProtocolUI/commit/f699647f9b0aa25b9782598e0cd4c3b8c002f24d
hotfix for now. will look after weekend to handle it more properly

**Comment by sirpy** [comment]
@L03TJ3
How is it possible that we have missed this issue so far?
It looks like something broke, an upgraded package?

**Comment by L03TJ3** [comment]
There are a couple of reasons why this could have been missed.
the most logical/easy one is that with my own testing of wallet-connect, I clear the cache pretty consistently so this particular issue does not come into existence.

**Comment by L03TJ3** [comment]
Now its run before connecting / after disconnecting: https://github.com/GoodDollar/GoodProtocolUI/commit/da8049d9876c5eb6ec307ec961b63ea04b3da6e9

It could still happen when user navigates within the modal. issue open here: https://github.com/WalletConnect/modal/issues/15

**Comment by L03TJ3** [comment]
Closing as their has been no reports of this being an issue
