### ISSUE TITLE
Finalize uniswap-widget

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#434]
**Description**
we wanted to have an MVP up because liquidity as being moved already
some left-over todo's are:
- [x] - add analytics
- [ ] - fix logo's missing when using custom-token list: https://github.com/Uniswap/widgets/issues/602
- [ ] - add error handling

**Comment by vldkhh** [comment]
@L03TJ3 still reproduces on dev 
![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/b3cd7165-f08a-456c-b1d0-31b9b2e349ee)

Also 'null' errors appear 
![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/2587ab0b-67ea-42a5-a573-d5ea7cf9ce08)

**Comment by sirpy** [comment]
@vldkhh the lockdown-install is not related to us, it must be some extension you have
@L03TJ3 i think we might need to fix the Logo link from the list we use, verify that Celo logo link in the list is working

**Comment by L03TJ3** [comment]
@sirpy The link is fine
its just caused by this issue: https://github.com/Uniswap/widgets/issues/602

**Comment by sirpy** [comment]
@L03TJ3 the issue you opened on uniswap doesnt describe what causes it only that it happens.
when I look at the console logs you supplied i see a lot of fetching of "pngs" returned with 404 which means it wasnt able to fetch the logos.

**Comment by L03TJ3** [comment]
I don't know what causes it... All I know is so far is that when using a custom list:
1. the DEFAULT native token logo suddenly stops working
2. adding the native token to the list, have it show up twice but the link still sometimes works/doesnt work


I have not gone over the full list yet to see which png are loading up or not

**Comment by L03TJ3** [comment]
@decentralauren when considering re-enabling the swap we should re-test current handling of errors / transactions failed etc.

The logo issue is opened a year ago, 0 response. don't think that will be fixed (by them)
@vldkhh maybe for you to re-test (fuse/celo widgets)

**Comment by decentralauren** [comment]
@vldkhh can you get with Lewis on what needs to be tested so that we can include this work as part of relaunching Swap next week?

**Comment by decentralauren** [comment]
Fine to not display currency logo as issue is unresolved on Uniswap's side.

**Comment by vldkhh** [comment]
verified on dev
