### ISSUE TITLE
Remove the data card from the claim flow

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#435]
The data displayed is hard-coded and confusing to our users. Let's remove it to simplify.

https://gooddapp.org/#/claim

<img width="518" alt="Screen Shot 2023-06-23 at 11 38 29" src="https://github.com/GoodDollar/GoodProtocolUI/assets/49105975/95d908c4-85b3-4420-b78f-b67eae93ff5c">

**Comment by L03TJ3** [comment]
done here: https://github.com/GoodDollar/GoodProtocolUI/commit/1a503d46df194b5f5b9ca0cee499b0e46879807f

**Comment by vldkhh** [comment]
@L03TJ3 @patpedrosa checked on dev, ready to deploy

**Comment by L03TJ3** [comment]
Removing the data card broke the ui on mobile a little
need to fix

**Comment by L03TJ3** [comment]
ui-fix done here: https://github.com/GoodDollar/GoodProtocolUI/commit/68be58ac2b0315f9845674dba383b0f8da40271b

**Comment by vldkhh** [comment]
verified on qa
