### ISSUE TITLE
Update menu

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#436]
**LW**

- [x] Add Donate page
Link: https://gooddollar.notion.site/Donate-to-a-G-Cause-e7d31fb67bb8494abb3a7989ebe6f181

- [x] Add Save G$
Link: https://app.halofi.me/#/challenges?tokensymbol=gd

- [x] Create Submenu Bridges
- [x] Add Squid Router
- [x] https://v2.app.squidrouter.com/

- [x] Create submenu More
- [x] Move Wallet, rename to GoodWallet
- [x] Move Docs
- [x] Move GoodAirdrop

**SW**
- [x] Add LW changes listed above
- [ ] Add bottom navigation bar (which is currently featured flagged on simpleapp) to gooddapp.org

**Comment by L03TJ3** [comment]
@patpedrosa @SanaJamm
Is the design done for this?

**Comment by SanaJamm** [comment]
This is the correct design for the dropdow.

<img width="247" alt="Screen Shot 2023-12-06 at 13 09 59" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/be6b6ce3-ecbe-4008-a40f-aa969fe562d3">


and there's a big vertical gab right now between the two dropdowns (bridges and more).
all vertical gaps  between menu list items should be 16px

**Comment by vldkhh** [comment]
verified on prod
