### ISSUE TITLE
make data available for dashboard via thegraph or other sources

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#44]
1. Interest reserve received 
2. G$ generated from interest
3. G$ minted from the decline of the reserve ratio
4.  Disco length cycle 
5. Disco time left for the current cycle 
6. Current G$ amount in Disco

**Comment by sirpy** [comment]
@drptiago this is ready
can you add those graphs?
4+5 are just display values, meaning no graph, just the current value

**Comment by drptiago** [comment]
These info are collecting and inserted in the DEV dashboard:

https://datastudio.google.com/reporting/a742cbcf-ce03-4f8f-a31d-2d9ea376d9e1

Disco time left for the current cycle -> Is in reality the number of days running in this cycle.

In trust fund:
![image](https://user-images.githubusercontent.com/62208156/144140078-c6d1db6c-b69b-4431-8c9b-acc32453fd03.png)

In token:
![image](https://user-images.githubusercontent.com/62208156/144140107-8dae7e07-8280-4298-8d49-aa6f178a3acd.png)
