### ISSUE TITLE
Bug: metamask mobile and wallet-connect v2

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#443]
**Bug Description**
Its not an issue on our side, but this issue is created for the task of testing/bumping onboard packages to latest versions when all is fixed

Metamask mobile has known issues when trying to connect with gooddapp (any dapp)
Current status
1. it has to have the same network selected in both wallet/dapp
2. switching from dapp breaks the flow/connection
3. switching from the wallet works

onboard thread: https://github.com/blocknative/web3-onboard/issues/1783
Metamask threads:
1. https://github.com/MetaMask/metamask-mobile/issues/6655 
    - the upgrade for wc monorepo packages (to 2.8.4) is already done in this pr: https://github.com/GoodDollar/GoodWeb3-Mono/pull/99

**Comment by vldkhh** [comment]
@L03TJ3 I see that sometimes the claim is working just fine (tx appears in MM), sometimes it does not appear at all, and sometimes I got JSON RPC error on the fuse chain. Take a look:
https://gooddollar.slack.com/files/U03L9737V08/F05GY43QC66/rpreplay_final1689268307.mp4

**Comment by L03TJ3** [comment]
@vldkhh where did you test this? dev/qa ?

**Comment by vldkhh** [comment]
see no issues with MM on prod
