### ISSUE TITLE
[BUG, mobile] Uniswap. The 'Review swap' popup doesn't fit the screen on Safari 

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodProtocolUI#447]
[BUG, mobile] Uniswap. The 'Review swap' popup doesn't fit the screen on Safari 

Steps:
1) go to gooddapp.org on safari
2) connect the wallet
3) go to the swap page and select the token to swap
4) click on the review swap button 
5) observe the result

Actual result:
The popup doesn't fit the screen 

Expected result:
The user is able to swap without any issues

Env:
iPhone 13 Pro Max // iOS 16.5.1 
iPhone 12 Pro Max // iOS 16.5.1

Attachments:
![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/864c6a04-ce75-4b3d-9afe-fe8bd6318013)
![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/867fc9bc-9986-4a95-8906-6c2f7a016d31)
https://gooddollar.slack.com/archives/C02KASD3Z7B/p1689608033569289

**Comment by L03TJ3** [comment]
Potentially fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/3c7ab04557ec9eacc9a30db6b199ade4db0193e5

**Comment by vldkhh** [comment]
@L03TJ3 the new popup doesnt fit the screen anyway, Also - {title} typo?
 ![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/51585c8f-9547-4678-ac3a-06bdd8cc185e)
![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/4c0e07db-3b84-4b17-a4a8-5dd3a1e4b3f4)
![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/94d4ee6e-9131-42e2-b39c-7ae11c0844e0)

**Comment by vldkhh** [comment]
verified on prod
