### ISSUE TITLE
Simple app to be embedded in wallets

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#455]
- [x] no wallet connect, automatically connect to injected wallet
- [x] no bottom bar/menu
- [x] show actions to do after claim screen
- [x] Hide Continuation Flow (swap cusd)
- [x] Hide Cards
- [x] Feature Flag Bottom Nav
- [x] Feature Flag Wallet Chat

**Comment by vldkhh** [comment]
@patpedrosa Do we want to keep the news feed in this app or remove it?

**Comment by decentralauren** [comment]
@sirpy Can we include the menu for the simple app minipay JUST for the T&C and privacy policy (disable others)?

**Comment by sirpy** [comment]
@decentralauren @patpedrosa 
The reason for not having a menu is not a technical issue. It is for not confusing the user with options that they simply wont be able to use. you can decide on whatever product requirements you need for simpleapp.

What is simpleapp general vs simpleapp minipay, i'm not familiar with the concept of simpleapp general.

**Comment by L03TJ3** [comment]
@sirpy simpleapp general is ment to be a version with all functionalities but connect (eg. mm browser etc)

**Comment by L03TJ3** [comment]
Ye well, tbh, at this point the difference is the bottom nav bar.

I also have mistested as I thought mm was able to auto-connect like it works on minipay

The mistest was that I had my account already connected before
