### ISSUE TITLE
Bug: mobile viewport does not fit screen

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#460]
**Bug Description**
recent UI changes broke viewport on mobile and cut-off bottom on all pages

**Comment by L03TJ3** [comment]
fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/d49caac0e9b41d08d607e31fb75b4922b6c797aa

**Comment by vldkhh** [comment]
verified on prod
