### ISSUE TITLE
(Bug) FV failing on mobile with not enough information

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#466]
The following error happens only mobile
https://gooddollar.sentry.io/issues/2174107180/events/?alert_rule_id=1208119&alert_type=issue&notification_uuid=175cebbc-0586-4917-ab58-015fba983166&project=1829798&referrer=slack

The error message is:
`Session could not be completed due to an unexpected issue during the network request.`

**Note
When looking at the server logs for some of these users there are no requests besides to "check face disposal sate"
So it looks like the error might be somewhere between that call and the next expected fv server call. (session token?license?)**

There are a few things to investigate and fix here:
- [x] why is this error only shown on mobile
- [ ] the whole handling of reject/success in ProccessingSubscriber is WAY too complicated, it is not clear at all if on web errors are at all logged. I can not find any mentions of this error in amplitude
- [x] this error seems to be a default message when unknown error occurs, we need to
    - create a better error message with more information
    - pass the complete server response to be handled by the dapp higher levels so the error can easily be customized and inspected
- [x] this error message is hard coded in two places in our code, we need different error messages with more information

**Comment by johnsmith-gooddollar** [comment]
@sirpy @vldkhh 

Yes the same error message was hard-coded in 2 places and there was no option to diversify it
I've adjusted error handling, now it's 2 messages about server error on session start / end
I cannot return json response, so now I return error message we receive from GoodServer

According to the behaviour it's an error during session token retrieve. It may be caused of 2 reasons a) outdated SDK - I've updated them b) wrong encryption key ? 

I hotfixed fv package and app, let's see which errors we're receiving now and which is server message.

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar @sirpy 
Just tested prod apk, the same issue persists. 

once clicking on verify (on the oval screen with the lady face), it just immediately jumps to 'something went wrong'

@vldkhh your video failed to upload

**Comment by johnsmith-gooddollar** [comment]
1. after login been update I saw the error is related to the session start (retrieve e session token) and the message is `org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject`. 

that means we got some HTTP error from heroku returned as html page.

2. in the log tail I found

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3JKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bdb19e840ec855d06737049bd2f2d19dee4abee4/image.png)

testing such double slashed urls I found they really produced 404 'page not found' printed as html

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a6e787edeec742bc9b5b7990590e63e6d2659536/image.png)

3. why this happens ? we have unbtrailed server urls set in env.xxx but in Vercel they're set with trailing slash.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEhKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1470102dac3613266ac562c4c5b0c0d8cb481fe7/image.png)

pulling verbal env overwrites the original value

Why it worked for some time ? No exact answer, most probably Heroku was tolerant for such //-started urls, then they fixed it.

4. I've hotfixed issue with removing trailing slash just before we pass server url to the Java module. 
https://github.com/GoodDollar/ReactNativeFaceTec/commit/eb83b33883f3893eba1e6070288256644c387c00
https://github.com/GoodDollar/GoodDAPP/commit/30f078c15068abfd626f85b05e0a76f3dfe2ca23
 
I also suggest to ensure `REACT_APP_SERVER_URL` in all places is set without trailing slash and fix if need @L03TJ3

**Comment by johnsmith-gooddollar** [comment]
It’s a feature of facetec
Total blank if low lights
Total black if too bright

**Comment by vldkhh** [comment]
verified on prod
