### ISSUE TITLE
Add link to Privacy Policy & Terms and Conditions to GoodDapp

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#468]
We need to display a link to the Privacy Policy and to the Terms and Conditions on GoodDapp per legal request.

"Privacy Policy" => https://www.gooddollar.org/privacy-policy
"Terms and Conditions" => https://www.gooddollar.org/terms-of-use

**Comment by L03TJ3** [comment]
fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/fde1e9e8806affb4b3848b7b37cac64c4f7bc199
