### ISSUE TITLE
Chore: update onboard packages for latest wc fixes

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#469]
**Bug Description**
This got fixed: https://github.com/blocknative/web3-onboard/issues/1783#issuecomment-1743761627

**Comment by L03TJ3** [comment]
fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/05dbb777d6420fab32fd14786b48e5bbd8ebf2dc

**Comment by kr-keshav-kk** [comment]
@L03TJ3 when can we expect this bug to be fixed?

**Comment by L03TJ3** [comment]
@kr-keshav-kk 
is live already

![image](https://github.com/GoodDollar/GoodProtocolUI/assets/6606028/9de0f3bb-1341-497a-ad4f-8339e8c96a87)

if you request a transaction from gooddapp that is from a different chain then your metamask, above modal should show up to first switch > then confirm transaction

you experience something different?

**Comment by kr-keshav-kk** [comment]
I follwed this [issue] (https://github.com/blocknative/web3-onboard/issues/1783) and came here. Mobile MM is not showing any pop up when network switch is triggered from my webapp. Do you have any solution? I am using svelte.

**Comment by sirpy** [comment]
@kr-keshav-kk i believe network switching on wallet in case of walletconnect is not required.
your dapp is supposed to put in the initial connection props the requirednetworks and optional networks.
when you send a tx it is supposed to include the target chainid and the wallet then knows on which network to execute it

**Comment by L03TJ3** [comment]
@kr-keshav-kk 
MM pops up a switch modal **only** when trying to send a transaction for a different chain then is currently selected in the users wallet. 

the switching itself is not an event anymore which does this as @sirpy says: a dapp/wallet now sets required/optional chains that are supported by either wallet/dapp

**Comment by kr-keshav-kk** [comment]
@L03TJ3 @sirpy is there any way i can call the network change pop up just after connecting MM?  I am using MM to sign a message and then send a transaction.

**Comment by L03TJ3** [comment]
you could look at: https://usedapp-docs.netlify.app/docs/guides/transactions/switching%20networks/
which is what we used before.

but I don't think that is relevant and metamask automatically does the switch chain when the request is from another chain

**Comment by vldkhh** [comment]
verified on prod
