### ISSUE TITLE
[Design QA] Modal Cards (desktop) 

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#472]
Change padding between the first header and the second to 8px.

Devs:
<img width="697" alt="Screen Shot 2023-10-17 at 10 59 23" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/365c0a29-3fe2-4764-8a8d-5ed84b0aff5d">

Design:
<img width="978" alt="Screen Shot 2023-10-17 at 10 30 27" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/cb162083-4da4-47b1-a58f-20f7be84c100">

**Comment by vldkhh** [comment]
verified on prod
