### ISSUE TITLE
[Design QA] Side menu (desktop)

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#473]
Issue 1
- [ ] Let the side menu extend to the bottom of the screen always:
![sidebar](https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/b9a26275-3d86-4c3e-a04b-e2bb2a709f2e)

Issue 2:
- [ ] Privacy policy and T&C should stick to the bottom of the side menu with 16px padding from the bottom 

Devs: 
<img width="258" alt="Screen Shot 2023-10-17 at 11 08 54" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/03f6624c-586b-455c-9a50-9db125af15df">

Design:
<img width="317" alt="Screen Shot 2023-10-17 at 11 08 24" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/791fa8a5-cf3f-4346-a890-6f9f08bfaf00">

**Comment by SanaJamm** [comment]
can you give me the link to check it? in the link i have nothing changed, even though Lewis sent me screenshot of something else.
this is the link i have:

https://good-swap-9ydt52ssf-gooddollarteam.vercel.app/#/claim

**Comment by L03TJ3** [comment]
@SanaJamm https://dev.gooddapp.org

**Comment by SanaJamm** [comment]
Confirmed. thanks!

**Comment by vldkhh** [comment]
@Sana could you verify new designs on prod? for me it looks fine

**Comment by SanaJamm** [comment]
![WhatsApp Image 2023-10-26 at 11 14 14](https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/00a37df5-7944-4d3f-90f0-e76c0455968b)

this is how i see it on my mobile..part of the side menu is hidden at the bottom

**Comment by L03TJ3** [comment]
@SanaJamm please share model/device etc. for this stuff there is not one solution which works everywhere

**Comment by SanaJamm** [comment]
my mobile is iphone 13 pro max, if the only solution for this is to keep it like before (to be above the connect wallet) then i think it's better to restore it, because we cant risk having this part cut.
sorry for the trouble

**Comment by vldkhh** [comment]
verified on prod. iPhone 13 Pro Max
