### ISSUE TITLE
[Design QA] Modal cards (Mobile)

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#474]
make the the horizontal padding for the cards 0px.

Devs:
![WhatsApp Image 2023-10-17 at 11 16 57](https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/1517a7df-9b42-422f-8391-4adb7a980f49)

Design:
<img width="191" alt="Screen Shot 2023-10-17 at 11 20 04" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/814e3c75-d3d9-4fb6-81d7-d1a4628459b2">

**Comment by vldkhh** [comment]
verified on prod
