### ISSUE TITLE
UI: viewport is not responsive on all mobile screens

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#476]
**Bug Description**
viewport does not adjust correctly to different screen sizes
either it causes a large white space at the bottom
up untill it cuts of the bottom part

**Steps to Reproduce**
1. Go to gooddapp
2. use devtools and switch to mobile view. Compare ultra20+ to iphone SE

**Comment by L03TJ3** [comment]
fixed in pr for simple app: https://github.com/GoodDollar/GoodProtocolUI/pull/477

**Comment by vldkhh** [comment]
@L03TJ3 Is this the correct responsive for mobile? 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFJnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ab5351f29edeb9714bc7437c35982cc61c71e85/E04FD3DC-58F3-4F13-82DB-6C676A5A8D1B.MP4)

**Comment by L03TJ3** [comment]
@vldkhh jup, seems like it :)

**Comment by vldkhh** [comment]
verified on prod
