### ISSUE TITLE
[Design QA](Mobile) carrousel buttons should trigger both directions

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#478]
**Bug Description**
A left and right arrow button is added to the claim-carrousel pagination slider.
but it only triggers a slide to the right

**Comment by L03TJ3** [comment]
fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/2e1974700f09bfb7a2e28e1331330e6d5dacf49e

**Comment by vldkhh** [comment]
verified on prod
