### ISSUE TITLE
[Design QA](Mobile) Open menu 

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#481]
please make the opened menu extend to the bottom of the screen with the same behavior and devision as the desktop version

Devs:
![IMG_3128](https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/b0cdfd98-4e9d-4ede-94b6-dfe5334bfab4)

Design:
<img width="262" alt="Screen Shot 2023-10-24 at 15 45 21" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/f93c5737-1c84-4967-b7a7-8c7d28849c48">

**Comment by vldkhh** [comment]
verified on prod via iPhone 13 Pro Max and Mi9
