### ISSUE TITLE
Buy widget review

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#491]
- the initial value in the calculation is hardcoded to 100 but should be correctly calculated.
 - The FAQ seems too long and not formatted
 - There's no contact form link for help
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5a3afca716554ce831f651803f0953c53358cb5/image.png)

**Comment by L03TJ3** [comment]
@patpedrosa @SanaJamm
1. can I expect a updated FAQ?
2. form link, where to place? (just at the bottom of faq?)

**Comment by vldkhh** [comment]
@L03TJ3 confirmed that calculation is fixed 
<img width="1528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTR1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3437fa9aa93883ac8ae2097094c8c507ca8d562e/Snag_44c18ec7.png" alt="Snag_44c18ec7.png" />
@patpedrosa @SanaJamm what about Lewis's last comment?

**Comment by decentralauren** [comment]
@patpedrosa I'm happy to! What copy needs to be reviewed? And is this for accuracy, tone, all of the above?

**Comment by decentralauren** [comment]
To add more detail in FAQ

https://docs.onramper.com/
Varies per payment provider
Varies per country and jurisdiction

**Comment by decentralauren** [comment]
@patpedrosa mind reviewing my updated FAQs? Also running by comms for a quick check.

https://www.notion.so/gooddollar/Update-FAQ-content-on-Buy-G-page-b3351b6ff9eb45d28970087af1345d6d

**Comment by vldkhh** [comment]
verified on prod. continued here #502
