### ISSUE TITLE
[Design QA] Buy G$ (Calculator)

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#496]
right now the default calculator shows before typing an amount 100cUSD=100G$, which is not correct and can confuse the user.
let's show as a default how much 1cUSD is in G$ 

Devs:
<img width="404" alt="Screen Shot 2023-11-28 at 13 42 32" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/fb48d4aa-60e0-4d9b-8986-1f838cc96db9">

Design:
<img width="410" alt="Screen Shot 2023-11-28 at 13 42 45" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/01c898f9-c95c-42b6-9789-63aed437fcf6">

**Comment by L03TJ3** [comment]
Already mentioned here: https://github.com/GoodDollar/GoodProtocolUI/issues/491
so closing for duplicate :)
