### ISSUE TITLE
[Design QA] Buy G$ / Desktop

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#497]
the drop down button should change when clicking the calculator and the FAQ  (the arrow and the color).
and let's make a the vertical gap between the two buttons 24px

devs:
<img width="404" alt="Screen Shot 2023-11-28 at 13 59 26" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/4bf6b679-a5a6-40ce-b596-5850147d4f0b">

design:
<img width="484" alt="Screen Shot 2023-11-28 at 14 21 46" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/a976a0e5-97ea-40ea-aaf1-3f49dfdb8198">

**Comment by vldkhh** [comment]
@L03TJ3 @SanaJamm we need to remove scroll bar here<img width="499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGs3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8633730cceb14f07d3966f280377ace42e44dda4/Snag_4ebc963e.png" alt="Snag_4ebc963e.png" />

**Comment by vldkhh** [comment]
verified on prod
