### ISSUE TITLE
Expose Wallet Balance in GoodDapp & Simple Dapp

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#498]
Currently MiniPay and GoodDapp mobile users can only see their cUSD / CELO balance (respectively) - which leads them to confusion after a claim, as their main balance doesn't change.

This issue is to implement GoodDollar wallet balance to the dApp (simple, mobile and desktop) at the header bar, and allow the user to tap / click to expand and see all GOOD-related tokens.

**Comment by L03TJ3** [comment]
@patpedrosa Is this about the top-left price?

**Comment by decentralauren** [comment]
Figma file https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=10460-4892&mode=design&t=9RlPGpxKGpAdu5AB-0

**Comment by decentralauren** [comment]
@L03TJ3 updated title - you're right it should just be displaying balance not conversion.

**Comment by SanaJamm** [comment]
this is the figma file for this card:
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=10159:4857&mode=design#658583658

to explain the animation of how this acts..
when pressing the wallet icon, the window slides down. it closes when pressing the wallet icon or anywhere on the screen.
if the user presses on the menu button while the wallet balance is also open, then it closes and the other way around.

**Comment by vldkhh** [comment]
@L03TJ3 @patpedrosa @decentralauren verified on dev 
<img width="338" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXFwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93ed8dd4dcfaa49e27f313421ec1bd5a5b8457e0/Snag_7c5ca536.png" alt="Snag_7c5ca536.png" />

**Comment by L03TJ3** [comment]
@decentralauren @patpedrosa @SanaJamm

Kindly do the qa review, this is the last item to be PR'd before release today

**Comment by SanaJamm** [comment]
I'll add to Pat's comment.. not only that the balance is not centered with the icon. but everything in the top navbar doesn't seem center aligned.
the space below the logo, balance and menu seems larger than the topper part

**Comment by L03TJ3** [comment]
@SanaJamm 
2. noted
1. We are talking just the mobile view not aligned right? desktop is fine?

**Comment by L03TJ3** [comment]
@SanaJamm 
This should be it right?
![image](https://github.com/GoodDollar/GoodProtocolUI/assets/6606028/616a9c00-2dc9-4c07-864c-15b86379f38d)

**Comment by vldkhh** [comment]
verified on prod
