### ISSUE TITLE
Choose UI kit

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#5]
- [x] show case 3 major ui kits (tailwind, etc)
- [x] explain drawbacks and advantages of each system

**Comment by thaddaeusus** [comment]
I have reviewed a lot of mature and maintained ui-kit's for Vue, picked the best and [made a sample app](https://github.com/vikseriq/uikits-demo) to let us try them at once and make final decision by the team vote.

**Comment by sirpy** [comment]
went with bulma
