### ISSUE TITLE
Remove USD balance from post-claim screen

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#509]
<img width="1336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9e4e4cf5c334544030d182ee38a89bcd5fae43d/Screen%20Shot%202023-12-19%20at%2009.23.38.png" alt="Screen Shot 2023-12-19 at 09.23.38.png" />

**Comment by vldkhh** [comment]
verified on prod
