### ISSUE TITLE
Dapp Menu adjustments

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#510]
1. Make menu open full width on mobile
2. add more social media icons to the bottom of the menu above privacy policy and T&C

links to the icons are below the design on figma

<img width="329" alt="Screen Shot 2023-12-19 at 17 14 42" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/d1aa1a8c-0ab0-444a-b460-723e0b3b2884">

Figma:
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=10680:64595&mode=design#650460916

Links that should be used (bitly) are available here: https://www.notion.so/gooddollar/9a11ade7a2e247d3aeee137d7cf07cb8?v=8ce41a466d18486bbfdfa127eea21ded&p=bdf86ff02fa44b5390e5ee58be105744&pm=s

**Comment by vldkhh** [comment]
@L03TJ3 walletchat and social icon overlapped. Suggestion - remove walletchat icon when the menu is opened and show walletchat only for main pages. 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20f1722e820b525e6577d17c9c041e160ad6eedd/image.png" alt="image.png" />


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOCtwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dca069bfcfec7e24cae73df534b61e6050f4303/2700AC05-D570-4A37-AB9A-AFBA506507B2.MP4)

**Comment by L03TJ3** [comment]
@vldkhh yes ok, good suggestion. will fix

**Comment by L03TJ3** [comment]
fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/5c699078d7e8eb02c957b8b7d11f1405d08f3b45

**Comment by vldkhh** [comment]
verified on prod
