### ISSUE TITLE
Fix Supply on Dashboard

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#513]

**Comment by decentralauren** [comment]
Fix data in Supply area for https://dashboard.gooddollar.org/ > Token 
- data is currently inaccurate
- subgraph needs to be updated

Should include
What's on Ethereum
What's on Fuse
What's on Celo

% of each

**Comment by drptiago** [comment]
The numbers seem right for me. What exactly is wrong?  
@decentralauren 

I did add %


![image](https://github.com/GoodDollar/GoodProtocolUI/assets/62208156/e49d4bdf-daae-49fd-9b65-88c37f0751d5)

**Comment by decentralauren** [comment]
Thanks @drptiago - when I created the ticket the split between chains wasn't visible. If Hadar confirms the numbers this ticket can be closed!

**Comment by L03TJ3** [comment]
this graph is no longer shown? so closing? @drptiago @decentralauren ?

**Comment by drptiago** [comment]
Supply received an entirely new dashboard
