### ISSUE TITLE
Update Page Layout for GoodDapp (title & description)

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#519]
We want to add more context to GoodDapp so that users know how they are interacting with GoodDollar and get extra content such as faq, links, and videos.

We're proposing implementing a framework that uses existing components (headline, subhead, dropdowns) and styling (fonts, proportions) defined by Sana - with the purpose of making it easier to implement.

Figma: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=10459-3581&mode=design&t=OvORKDuXB2adTWob-0

The idea is that the main component will live in the "grey" area, while the right side will be populated with content.

We want to implement it first to the swap and the stake pages. If there's no copy on the dropdowns, they should not show.

**Comment by SanaJamm** [comment]
I made several breakpoints examples:

https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=10459:3581&mode=design#670123421 

on my opinion the menu should open half width on tablets:
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=10459:3581&mode=design#670131937

**Comment by drptiago** [comment]
**About events and tracking.**

If we will add new menus in the left menu ( image below), lets follow the same pattern:
```
goto_claim
goto_swap
goto_fuse_bridge
goto_squid_router
```

Right now, all menus in production have the proper events.
![image](https://github.com/GoodDollar/GoodProtocolUI/assets/62208156/c94994d9-7777-4c4c-811f-9ebddf4d9b0e)


In the new "dropdowns" we can define a patter like:
dropdown_<page>_<content>

Examples in the image below:
```
dropdown_swap_dropdowns1
dropdown_swap_video_guides
dropdown_swap_faq
```

![image](https://github.com/GoodDollar/GoodProtocolUI/assets/62208156/a9bc9322-5a4d-4bda-b392-2315e0a78982)

**Comment by L03TJ3** [comment]
@SanaJamm @patpedrosa should be reviewed on production

**Comment by L03TJ3** [comment]
Ready for review on production @SanaJamm @patpedrosa

**Comment by decentralauren** [comment]
@L03TJ3 - should we close this and start new tickets for any UI issues we find moving forward (padding etc)? cc @vldkhh what do you think?

**Comment by decentralauren** [comment]
@L03TJ3 thanks - closing.
