### ISSUE TITLE
Add GoodDapp External Link Redirect Notice

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#520]
We need to add a redirect notice for external links displayed within GoodDapp. Let's use our existing modal design (styling/buttons).

______
**Redirect Notice**

By accessing this link you are leaving gooddapp.org and are being redirected to a third-party, independent website.

(GO TO WEBSITE)
______

**Comment by SanaJamm** [comment]
@patpedrosa this appears as a modal right?

**Comment by SanaJamm** [comment]
Link to design:
@patpedrosa let me know if it's ok.

https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC?node-id=11678:26769&mode=design#670107959

**Comment by L03TJ3** [comment]
updated link here: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=11685%3A64915&mode=design&t=X5afPIlIuMjiAFZ4-1

**Comment by L03TJ3** [comment]
@patpedrosa Should this include everything like news-feed items / claim cards as well?

**Comment by vldkhh** [comment]
verified on QA

**Comment by vldkhh** [comment]
verified on prod
