### ISSUE TITLE
"Buy G$" to redirect to Squid Router

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#521]
We want to have a menu item on GoodDapp called Buy G$ that redirects users to Squid Router. This is an external link, and, as such, needs to display the external link redirect notice.

Let's also track clicks on the menu item.

**Comment by sirpy** [comment]
why is buy G$ = squid router?

**Comment by drptiago** [comment]
The click on the “squid router” is already being tracked by Lewis.

**Comment by L03TJ3** [comment]
@drptiago this is another one menu item where a click on 'Buy G$' redirects a user to squid router.
it added the event: "buygd_squid"
To track interest in buying of g$'s

**Comment by L03TJ3** [comment]
added here: https://github.com/GoodDollar/GoodProtocolUI/commit/f9c8f23f95b6d8c9014c8dba67863f69494017fe

**Comment by vldkhh** [comment]
verified on QA

**Comment by vldkhh** [comment]
verified on prod
