### ISSUE TITLE
[GoodID] location certificate

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#523]
Add an api endpoint to issue location certificate
inputs: 
- location data from browser
- user ip
- optional mobile number
returns certificate

Create a method to issue location certificate
- verify that location data from gps matches user ip geolocation
- if mobile number is given, verify that user mobile was verified and matches our stored hash
- if gps+ip resolves to same country or mobile is verified, then use the country from gps or mobile country code
- issue certificate using veramo.io sdk

**Comment by johnsmith-gooddollar** [comment]
External services required
- to get client IP + country data (we may use one to get ipv6 for captcha, need to check does it provides country info)
- to get country from location coordinates (google reverse geo coding or find other one as google have strict limits for the free usage)
- with mobile phones everything looks fine - just check country code from the number (we may have this list at the phone input)

**Comment by johnsmith-gooddollar** [comment]
1. we're already using an external API to get country from IP address - won't change
2. for reverse geo coding I suggest to use https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=-34.44076&lon=-58.70521 It's free and open, does not requires You to create any account

**Comment by johnsmith-gooddollar** [comment]
> @johnsmith-gooddollar In the case where gps+ip AND verified mobile differ, which one takes precedence?

data from the phone. actually if user have verified mobile, we don't even check gps and IP

**Comment by decentralauren** [comment]
@L03TJ3 why is this on hold?

**Comment by L03TJ3** [comment]
That was requested by @vldkhh when we have items moving up from technical-review but are not really 'qa-able' yet

**Comment by vldkhh** [comment]
verified on storybook

**Comment by vldkhh** [comment]
@L03TJ3 https://github.com/GoodDollar/GoodDAPP/issues/4260#issuecomment-2230696598

**Comment by vldkhh** [comment]
verified on prod
