### ISSUE TITLE
Update all texts to the following

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocolUI#53]
https://docs.google.com/document/d/1NJCj4MUQU8vwbtkfY_c9epSI_Ykfl2K4Zf1WaLCBFnk/edit

**Comment by mukulshakya** [comment]
Hey @tomerGD 

Texts for which new column in empty are unchanged?

**Comment by adaptivecodeio** [comment]
Exception seen during staking flow, currently investigating and will provide full analysis

**Comment by imanshu03** [comment]
https://github.com/GoodDollar/GoodProtocolUI/pull/64
