### ISSUE TITLE
Do not show "Leaving GoodDapp" modal when navigating to other G$ assets

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#536]
## Business Description
Remove "Leaving GoodDapp" modal when navigating to any GoodDollar managed domains or subdomains:
- gooddollar.org
- goodcollective.earth
- goodid domain

Update to[ Ticket 520. ](https://github.com/GoodDollar/GoodProtocolUI/issues/520)

## Open Questions:
[ ] @L03TJ3 any domains I missed?

**Comment by L03TJ3** [comment]
Fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/92e33455fc1ff0649919841eff6c07cc75f21e00

**Comment by vldkhh** [comment]
verified on dev

**Comment by vldkhh** [comment]
verified on qa

**Comment by vldkhh** [comment]
verified on prod
