### ISSUE TITLE
Enable staged roll-out of features to specific geographies & wallets using Post-Hog

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#541]
## To Do:
[ ] look into post-hog ability for A/B testing for both wallet listing and regional segmentation @L03TJ3 
[ ] could be that its possible to pass down a location? in that way it could re-use what we have done for our own check @L03TJ3 

## Business Description
We want to be able to test new features on a small group of "greenlisted" addresses before rolling out more broadly. We also want to be able to release new features to specific geographies in a staged manner. An imminent use case for this is testing the GoodID upgrade and offer functionality.

## Detailed Description of Functionality
*Provide detailed step-by-step functionality, including visual aids, edge cases, and special considerations.*
- (Includes link to Figma if applicable)
- (screenshots to describe step by step how the feature works if applicable)
- (edge cases)
- (special considerations / expectations)
- (Describe various state a feature/screen could be in)

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

 
## Acceptance Criteria
*Specify criteria that will be used to determine if the feature meets the requirements and functions correctly.*
- [ ] (Should include a list of testing points for QA how to verify design/functionality)

**Comment by decentralauren** [comment]
@L03TJ3 I just found this old ticket to support using Post-Hog also to control GoodID rollout so I think we can close it?

**Comment by L03TJ3** [comment]
@decentralauren yes, closing now
