### ISSUE TITLE
[GoodID] Update Dapp GoodID page post-upgrade

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#546]
## Business Description
After going through the GoodID Upgrade process, users will need the ability to:
1. view their upgraded GoodID, 
2. reference their FaceID number and to 
3. re-do / re-upgrade their FV process if interested

## Detailed Description of Functionality

[Figma ](https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=14818%3A99538&mode=design&t=tItvoOs01A318L2S-1)(WIP)
<img width="872" alt="Screenshot 2024-04-01 at 11 13 49 AM" src="https://github.com/GoodDollar/GoodDAPP/assets/149098646/51dc7fef-0b62-4921-b079-3f10be2cf026">

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

 
## Acceptance Criteria
- If location was unverifiable during upgrade flow, should display as Unverified
- If any values were disputed by the user during the upgrade flow, they should display as Unverified

**Comment by L03TJ3** [comment]
Closing this as its one component handling the state of pre/post upgrade.
This one is enough: https://github.com/GoodDollar/GoodProtocolUI/issues/547
