### ISSUE TITLE
[GoodID page] Redo Face Verification 

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#548]
## Business Description
Allow the user to redo their FV for the purposes of refreshing their GoodID expiry date or GoodID credentials. 

## Detailed Description of Functionality
*Provide detailed step-by-step functionality, including visual aids, edge cases, and special considerations.*
- (Includes link to Figma if applicable)
- (screenshots to describe step by step how the feature works if applicable)
- (edge cases)
- (special considerations / expectations)
- (Describe various state a feature/screen could be in)

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

 
## Acceptance Criteria
*Specify criteria that will be used to determine if the feature meets the requirements and functions correctly.*
- [ ] (Should include a list of testing points for QA how to verify design/functionality)

**Comment by L03TJ3** [comment]
@decentralauren isn't this now a duplicate of the updated good-id page: https://github.com/GoodDollar/GoodProtocolUI/issues/547

or is this ticket for specifically the upgrade button implementation?

**Comment by decentralauren** [comment]
@L03TJ3  no longer needed (per your last comment). Closing this ticket :)
