### ISSUE TITLE
[MicroBridge]: Fee amounts are not applied correctly

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#554]
**Bug Description**
The fee amount shows 50% of what is actually withdrawn.

To look into:
1. why is there a fee difference (in UI display) between dev wallet / dev gooddapp even though they interact with the same contract
2. why is showing a 'to-receive-amount' of 998.50 on a 1000 transfer?

**Steps to Reproduce**
1. Go to dev.gooddapp
2. Click on microbridge
3. connect wallet
4. connect to fuse (celo has a bug in decimal conversion)
5. fill in 1000
6. see to receive amount
7. execute
8. see transaction on explorer for the actual amounts used

**Expected Behavior**
The amount to receive should apply fees withdrawn correctly

**Comment by decentralauren** [comment]
@L03TJ3 this seems like something we should resolve before launching the MicroBridge - can you review?

**Comment by L03TJ3** [comment]
@decentralauren should already be in progress

**Comment by vldkhh** [comment]
verified on dev. @L03TJ3 all good? 
<img width="404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d62768c73f6a7d29cf41bbde5569af953d0226a5/Snag_3c2a09.png" alt="Snag_3c2a09.png" />

**Comment by vldkhh** [comment]
@L03TJ3 
![image](https://github.com/user-attachments/assets/5d379134-1470-47b1-9b0d-91ff8a19cd8c)

**Comment by vldkhh** [comment]
verified on prod
