### ISSUE TITLE
[Bug, mobile, WalletConnect]: Swapping fails to calculate gas correctly

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#555]
**Bug Description**
It seems that sometimes on mobile when connected with GoodDollar wallet (wallet-connect) there are connection issues.

1. confirmation in wallet shows immediately an 'Could not approve request'. (Seen on celo, screen 1)
2. after switching to fuse and trying to swap, the confirmation never shows up.
3. after switching to fuse it shows a modal 'this transaction will likely fail' (no screen available, does not happen all the time)
4. after disconnecting wallet and restarting wallet, try and reconnect on gooddapp. It could be the confirmation from point 2 still shows up (there is no active connection anymore)

It's not sure if the issue is in the wallet or gooddapp, so this should also be tested against another dapp (like uniswap)

**Steps to Reproduce**
1. Go to gooddapp (mobile)
2. Click on wallet-connect
3. connect wallet (android app)
5. try swapping

**Expected Behavior**
Swapping should work as expected

**Additional Context**
(Could not approve request)
![image](https://github.com/GoodDollar/GoodProtocolUI/assets/6606028/333ae7aa-9b80-470d-ae30-bcd592e04af9)

**Comment by L03TJ3** [comment]
@decentralauren what does your last comment mean? that it is given priority or that it should be decided on still.

I see its still in 'new issues', but I thought it was supposed to be in this current sprint correct?

**Comment by decentralauren** [comment]
@L03TJ3  I believe the question was whether to prioritize immediately or wait for this sprint, so yes it should be in sprint.

**Comment by L03TJ3** [comment]
@vldkhh Can you retest this, I have updated some stuff with rpc's which might have mitigated the issues

**Comment by vldkhh** [comment]
verified on prod
