### ISSUE TITLE
Update MiniPay access to GoodDapp

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#559]
## Business Description
MiniPay users need to access the full range of features in GoodDapp. We will remove the redirect of MiniPay users to a reduced version of GoodDapp without a menu and instead allow them to access the full GoodDapp through MiniPay

 
## Acceptance Criteria
*Able to Access GoodDapp using MIniPay, wallet is connected.
*Able to navigate to hamburger menu of GoodDapp using MiniPay
   - Should be able to claim
   - Should be able to swap
   - Should be able to see their GoodID
   - Should be able to see Hamburger menu
*Able to successfully navigate to GoodDapp pages through the hamburger menu of GoodDapp using Minipay
*Test both via "Featured dapp" part of MiniPay and through their "Explore" browser

**Comment by sirpy** [comment]
It is not as simple as that some features are Fuse only and I dont think they can switch chain.
So we need to evaluate what exactly is possible to expose to the minipay users

**Comment by L03TJ3** [comment]
Rejected based on swapping approval failing

**Comment by L03TJ3** [comment]
@vldkhh Test this please (dev)

**Comment by sirpy** [comment]
@decentralauren @L03TJ3 this was deployed no?

**Comment by L03TJ3** [comment]
@sirpy yes

**Comment by decentralauren** [comment]
@L03TJ3 why is this still open?

**Comment by L03TJ3** [comment]
@decentralauren I was waiting for any confirmation that it worked besides my own testing.

That is my general answer for the other similar questions as well

**Comment by vldkhh** [comment]
verified on prod
