### ISSUE TITLE
User should be able to select correct network

### ISSUE THREAD

**Issue by adaptivecodeio** [GoodDollar/GoodProtocolUI#56]
Acceptance Criteria

use NETWORK env variable

if NETWORK is staging then fuse contracts are read from the 'staging' key in the json

if NETWORK is mainnet contracts are read based on the user WALLET connected network: 

if NETWORK is kovan read kovan-mainnet 

if NETWORK is ropsten then staging-mainnet

if NETWORK is production then for fuse read production from the json

If NETWORK is mainnet(ethereum), read production-mainnet from deployment.json

**Comment by MayurAdaptiveCode** [comment]
https://github.com/GoodDollar/GoodProtocolUI/pull/57/files

**Comment by mukulshakya** [comment]
(production-mainnet) Ethereum network selection is currently disabled as contact addresses are not deployed

**Comment by adaptivecodeio** [comment]
@sirpy 

Please Review

**Comment by sirpy** [comment]
support for ethereum mainnet should be added if though contracts are not deployed yet.
@adaptivecodeio
