### ISSUE TITLE
New page for News Feed (move from Claim)

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#564]
## Business Description
For usability and more clear access to each feature, we are separating out the New Feed from Claim in GoodDapp (were previously on the same page). They were previously on the same page because the MiniPay dapp allowed useres to access only the "Claim" page on GoodDapp, which is changing as users will now be able to access the menu and select GoodDapp functionality (including this News page). 

## Detailed Description of Functionality
- "News" tab to be added to global nav of the page
- "News" to be removed from the "Claim" page

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

## Design Reference
@sanajamm will add in comments below.
 
## Acceptance Criteria
*Specify criteria that will be used to determine if the feature meets the requirements and functions correctly.*
- [ ] (Should include a list of testing points for QA how to verify design/functionality)
filled out by the development team or can contain suggestions._

## Test Cases
*Specify the happy path and unhappy path scenarios to test to verify the feature works as expected.*

**Comment by sirpy** [comment]
The claim page is our best asset to show news. if anything i'd move the last TXs to a separate tab.

**Comment by decentralauren** [comment]
It is unlikely people see it now accessing the Claim page by mobile, with all of the other info on that page.

I prefer that we direct users first to the News feed (IE have News be "Home," not "Claim") then have them navigate to Claim in the nav.

**Comment by SanaJamm** [comment]
@decentralauren @L03TJ3 

Mobile:
<img width="892" alt="Screen Shot 2024-07-16 at 14 52 53" src="https://github.com/user-attachments/assets/bcdb2fa8-742a-4028-8138-16f6b67c192f">

Desktop:
<img width="1039" alt="Screen Shot 2024-07-16 at 14 51 59" src="https://github.com/user-attachments/assets/f462e9a7-d603-4b84-ba4e-e45b4e4e7069">

Figma:
https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=19528-73612&t=ri63stIDIMgmBkWt-1

**Comment by L03TJ3** [comment]
@decentralauren fyi: we already have a transaction history under account details btw:


![image](https://github.com/user-attachments/assets/54aef504-5ee2-49d1-aacc-d9b7cfefa9be)

**Comment by L03TJ3** [comment]
added here: https://github.com/GoodDollar/GoodProtocolUI/commit/4b78fbe7d992436dd76b395c354763d529dd2847

**Comment by sirpy** [comment]
@L03TJ3 @decentralauren 
did we deploy already?
isnt this similar to #567

**Comment by L03TJ3** [comment]
@sirpy 
1. yes this is deployed
2. no, the other one is about showing a single (latest) news feed item on the post-claim screen. but that has been added to the goodid PR already: https://github.com/GoodDollar/GoodWeb3-Mono/pull/128

**Comment by decentralauren** [comment]
@L03TJ3 why is this still open?

**Comment by vldkhh** [comment]
verified on prod
