### ISSUE TITLE
(BUG) Staked G$ not showing on portfolio on Gooddapp

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#565]
1. [Reporting on slack first](https://gooddollar.slack.com/archives/C06QV47BVGB/p1721321065230629?thread_ts=1721267862.531459&cid=C06QV47BVGB)
 2. 2 users have reported this
 3. I also checked and did not see is staked G$ on is portfolio but he can see it on the explorer
 4. GoodDollar App version 2.42.0
5. 0xFf00A683f7bD77665754A65F2B82fdEFc4371a50

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVh3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7f9adc8d75eba5e1e521ddba191c0def6ea093e/Screenshot_20240719_004300_Chrome.jpg" alt="Screenshot_20240719_004300_Chrome.jpg" />

**Comment by L03TJ3** [comment]
@sirpy I am already on this and it seems like rpc issue (am in the middle of testing). I will keep you posted on status if not solved by tomorrow

**Comment by L03TJ3** [comment]
a fix has been pushed here: https://github.com/GoodDollar/GoodWeb3-Mono/commit/c0cce300eb9280845d23442394db884dce650ce1

@sirpy Maybe you know a better way to handle it.

It seems to be getting confused by passed down providers and using the wrong one when trying to fetch mainnet data. I likely missed a place where a provider was passed down but I could not fully trace where it was.

Why I for now (as a hotfix) did a forced local mainnet provider for fetching mainnet data

**Comment by decentralauren** [comment]
@vldkhh are you able to test this in dev?

**Comment by vldkhh** [comment]
@decentralauren I still don't understand the issue. If this is correct - then we can push fixes to prod
![Snag_3f21ed](https://github.com/user-attachments/assets/b09304ce-5872-4f0e-a519-a89c1e6f2dbb)

**Comment by L03TJ3** [comment]
@vldkhh already in prod. If active stake shows up > working
