### ISSUE TITLE
[Claim Flow] Display News Feed item in post-claim screen

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#567]
## Business Description
Since we are moving the News Feed from the Claim page in GoodDapp into its own page, we want to make sure that claimers still see / know about news items. As such we are introducing a news feed widget post-claim that displays the most recent New feed item, and includes a link to see all news. 

## Open Questions
- [ ] How does this work with "claim on other chain" functionality? @sanajamm
- [ ] Should this also appear in the GoodWallet1 or just GoodDapp (IE is it easier to build for both, or ok to build for just one)? @sanajamm

## Detailed Description of Functionality
- The most recent news feed item should display on the post-claim screen only when the user has claimed from all available pools.
- Clicking on the news feed item will take the user to the news feed item detail (same behavior as regular news feed)
- Clicking on the "see all news" button will take the user to the News tab

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

## Design Reference
@sanajamm to provide in comments
https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=20466-114369&t=DS7HRguDAzIYVNpQ-4
 
## Acceptance Criteria & Test Cases

 - [x] **Scenario: News Feed item displayed post-claim**
  - Given a user has claimed from all available pools
  - When the user accesses the post-claim screen
  - Then the most recent news feed item should be displayed
  
 - [x] **Scenario: News Feed item not displayed post-claim**
  - Given a user has claimed from some available pools but not all
  - When the user accesses the post-claim screen
  - Then the most recent news feed item should NOT be displayed, and instead the user should be able to try claim again

- [x] **Scenario: Clicking on news feed item takes user to news feed item detail**
  - Given a user has claimed from all available pools and sees the news feed item in the post-claim screen
  - When the user clicks on the news feed item
  - Then the user should be taken to the news feed item detail
  
- [x] **Scenario: Clicking "see all news" button takes user to News tab**
  - Given a user has claimed from all available pools and sees the news feed item in the post-claim screen
  - When the user clicks on the "see all news" button
  - Then the user should be taken to the News tab

**Comment by decentralauren** [comment]
@L03TJ3 assigning to you as I cannot assign to @sanajamm

Sana - please look at the Open Questions above, esp how to handle this with the "claim from other chain" button. Please explore and discuss with Lewis once you have a suggestion!

@L03TJ3 if you feel comfortable with the solution after working with Sana feel free to start on this in the current sprint

**Comment by sirpy** [comment]
@L03TJ3 @decentralauren wasn't this implemented?

**Comment by L03TJ3** [comment]
yes done here: https://github.com/GoodDollar/GoodWeb3-Mono/pull/128

**Comment by decentralauren** [comment]
@L03TJ3 closing as it seems this was implemented.
