### ISSUE TITLE
Governance Token is GOOD, not GDAO

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#67]
**Bug Description**
A clear and concise description of the bug:

Portfolio section disclose GOOD tokens as GDAO. Please refer to GDAO Rewards (or better, **GoodDAO Rewards**) when talking about rewards from the DAO (there where it now disclose GOOD Rewards), while when referring to the token itself, do it as GOOD tokens (not GDAO).

**
Steps to Reproduce**
It's just a texting issue in the Portfolio section of the protocol dapp
...

**Expected Behavior**
just replace GDAO with GOOD, while also replacing GOOD Rewards to GoodDAO Rewards (or GDAO in case of space contraints). 

**Additional Context**

<img width="1039" alt="Captura de pantalla 2021-12-03 a las 18 05 04" src="https://user-images.githubusercontent.com/22507864/144643171-9735b5c2-5d97-4bb3-85bc-4a83f4aa8d62.png">
<img width="1037" alt="Captura de pantalla 2021-12-03 a las 18 06 44" src="https://user-images.githubusercontent.com/22507864/144643412-0d15ebed-2202-42aa-80b2-4292a9aaa5d1.png">

**Comment by sirpy** [comment]
@womaninblockchain i believe that was fixed

**Comment by womaninblockchain** [comment]
Fixed

**Comment by sepu85** [comment]
closing
