### ISSUE TITLE
User should be able to stake G$ to earn GOOD

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#69]
todo:
- [x] ethereum header
- [x] claim rewards separated to etherem/fuse

Test Cases:

- [ ] Stake GoodDollars over fuse network
- [ ] Create new frame : GoodDollar Stake
- [ ] Create new column: Token
- [ ] Create new column: Protocol
- [ ] Create new column: Governance Weight
- [ ] Create new column: Blocked Liquidity
- [ ] Create new column: Total Rewards
- [ ] Create new button: Stake button
- [ ]  Create new button: Unstake button
- [ ] Showing portfolio/staking even if not connected to right network
- [ ] Staking position of G$
- [ ] Claim GOOD tokens
- [ ]  Claim rewards button to claim GOOD
- [ ] Claim rewards button to claim G$

**Comment by sepu85** [comment]
Description:
Add functionality for user to stake their GoodDollars over fuse network. This feature shall be able from the `Stake`(left panel) section.

Context:
<img width="1425" alt="Captura de pantalla 2021-12-14 a las 15 57 34" src="https://user-images.githubusercontent.com/22507864/146023037-d031b5e5-29b0-49ae-b96f-79013d25bab9.png">

while the current UI is seems as above, first we need to differentiate from staking4UBI and staking4GOOD governance. Therefore, the first request is to: 
[] change from `Stakes` to `GoodStakes`, as it is how we are calling the UBI staking.

in the same `Stake`section and below the mentioned GoodStakes (formerly called just `Stakes`) frame, create a new frame called `GoodDollar Stake'.

This second frame should have:
[] Tittle: GoodDollar Stake
[] It should have the following columns: `Token`(only GoodDollar), `Protocol`(only Governance), `Governance Weight` (How much percentage does user is gaining in governance according to Total Distribution), `Blocked Liquidity`(Total value staked in G$) and `Total Rewards` (Total yearly rewards in GOOD).
[] text bubbles are the same as in GoodStakes but modified accordingly to the info in the bullet above
[] Stake button
[] Unstake button
[] This frame should be disclosed only whe G$ tokens are detected in user's wallet.

**Comment by sepu85** [comment]
on portfolio section, user should:
[ ] disclose how is it's staking position of G$.
[ ] claim GOOD tokens

**Comment by mukulshakya** [comment]
Hey @sepu85, For ticket 69 i need staking contracts available for G$ token in FUSE(staging) namespace in deployment.json (ref img: https://prnt.sc/23eq6kq)

**Comment by sepu85** [comment]
@sirpy @galw can you provide? 👆🏼

**Comment by sirpy** [comment]
i'm working on this issue

**Comment by sirpy** [comment]
![image](https://user-images.githubusercontent.com/671095/146673155-90bb0f98-bece-4938-86c9-61fbf80e8743.png)
![image](https://user-images.githubusercontent.com/671095/146673163-420091ab-42ee-44ca-900c-9e3a7db848d2.png)
![image](https://user-images.githubusercontent.com/671095/146673184-c0f2a9f8-6408-440e-8f10-442476ac75df.png)
![image](https://user-images.githubusercontent.com/671095/146673486-e117b360-2aa7-445f-aebe-1ac7b3e64fe2.png)

**Comment by womaninblockchain** [comment]
Checklist to do:

- [ ] Stake GoodDollars over fuse network
- [ ] Create new frame : GoodDollar Stake
- [ ] Create new column:  Token
- [ ] Create new column:  Protocol
- [ ] Create new column: Governance Weight
- [ ] Create new column: Blocked Liquidity
- [ ] Create new column: Total Rewards
- [ ] Create new button: Stake button
- [ ] Create new button: Unstake button
- [ ] Showing portfolio/staking even if not connected to right network
- [ ] Staking position of G$
- [ ] Claim GOOD tokens
- [ ] Claim rewards button to claim GOOD
- [ ] Claim rewards button to claim G$

**Comment by sepu85** [comment]
@sirpy I'm testing this out now. I have two feedbacks:

1. When in a Non-Fuse network, the button is not disclosing the right variable:
<img width="979" alt="Captura de pantalla 2021-12-21 a las 10 37 46" src="https://user-images.githubusercontent.com/22507864/146907159-833687ce-b2d7-4072-ad10-19d0493bbceb.png">
it says "Switch to {Network}" instead "Switch to Fuse"
2. I tried to stake my G$s on Fuse, the app isn´t reading my balance, I guess this is not a real issue as contracts are not upgraded yet and this might fix that. Probably the point 1. as well, but just wanted to check this with you.
