### ISSUE TITLE
Remove Log on screen on QA website

### ISSUE THREAD

**Issue by adaptivecodeio** [GoodDollar/GoodProtocolUI#71]
Please disable the login page on http://fi-qa.gooddollar.org/

Success Criteria
A user should be able to access the website without being asked for a password

**Comment by mukulshakya** [comment]
PR - https://github.com/GoodDollar/GoodProtocolUI/pull/72

**Comment by womaninblockchain** [comment]
Works correctly. When entering the website it does not ask to log in
