### ISSUE TITLE
Setup dev env

### ISSUE THREAD

**Issue by adaptivecodeio** [GoodDollar/GoodProtocolUI#77]
Currently  github actions deploys the code to IPFS with "staging" env settings. 
It also updates fi-qa.gooddollar.org to point to the new IPFS file

- [x] create a similar process for the dev env.
- [x] process should be based on branches: dev, staging
- [x] use fi-dev.gooddollar.org

**Comment by sirpy** [comment]
@YpetrovAJ

**Comment by YpetrovAJ** [comment]
can you check the task [here](https://github.com/GoodDollar/GoodProtocolUI/blob/develop/.github/workflows/dev_deploy_release.yaml) pls? 

@sirpy

**Comment by YpetrovAJ** [comment]
https://github.com/GoodDollar/GoodProtocolUI/pull/120
