### ISSUE TITLE
Portfolio section: Separate "Claim Rewards" and "Withdraw Liquidity" from staking pools

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#81]
**Bug Description**
It is currently not possible to Claim Rewards without withdrawing liquidity from staking pool, also UX is not clear about gow many G$s are for the staker to claim his rewards.

**Steps to Reproduce**
1. Go to Portfolio
2. It's assumed user has already staked assets for generating UBI and the rewards program is ongoing.
3. Click on "Claim Rewards" as there is no option like "Withdraw liquidity"
4. User can't choose to Claim G$ Rewards without withdrawing his whole liquidit.
...
<img width="1025" alt="Captura de pantalla 2021-12-16 a las 12 26 00" src="https://user-images.githubusercontent.com/22507864/146363353-fcc65c15-5dc2-4ff5-84d2-513f6ec0d0a6.png">
<img width="707" alt="Captura de pantalla 2021-12-16 a las 12 35 24" src="https://user-images.githubusercontent.com/22507864/146364639-42cfbbe3-b151-466a-9729-3b5b349a1a21.png">

**Expected Behavior**
User CAN choose to Claim G$ Rewards without withdrawing his whole liquidity.
- [ ] Add a button where user can claim G$ rewards.
- [ ] Clarify is user can withdraw liquidity without taking rewards. One button to Withdraw and claim (as the current only "withdraw" experience is seems ok, what's not ok is having this as the only option for user.

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by sirpy** [comment]
@sepu85 i think tthis is a mistake and the button should say withdraw next to each protocol
at the first section there's a claim button only for rewards

**Comment by sepu85** [comment]
> i think this is a mistake and the button should say withdraw next to each protocol
I agree, in portfolio section, all rows (staking positions) should have a button saying `Withdraw`rather than `Claim reward`

> at the first section there's a claim button only for rewards
now I understand, nice. So that's a button that claim ALL rewards from ALL positions?? I believe we should have a dedicated `Claim Rewards` button per each staking position, but this is a new feature we could add to the backlog (let's talk this before opening a new issue, then).

in issue #42 I stated the following for the G$s reward, now I'm realizing the statement is wrong:

```
- G$ rewards
How much value your stake has accumulated so far
```

now, I'm not sure what's supposed to be there, could you @sirpy check configurations and tell me what exactly means that variable? then we ping @adaptivecodeio to update that issue.

**Comment by sirpy** [comment]
in the portfolio page at the top it shows your "all accumulated (claimed+unclaimed) rewards  from all contracts"
in the middle it shows you "claimable rewards"
per position it shows the "all accumulated rewards(claimd+unclaimed) from this contract"

Yes we need to reconsider the claim rewards buttons, that was a decision Tomer took.

**Comment by sirpy** [comment]
@YpetrovAJ 
Here the user need to have two buttons next to his stake position "Withdraw" and "Claim Rewards"
Needs a layout from the designer

**Comment by YpetrovAJ** [comment]
we've made claim rewards as the check box, it seems for us to look like better on the UX side, can you check it [here](https://www.figma.com/file/qQnLAqI49HHbvHr1o1xD1a/GoodDollar?node-id=31%3A463)?
