### ISSUE TITLE
G$ Rewards information in Portafolio / Ethereum staking is not correct

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#82]
**Bug Description**
The `G$ Rewards` column's data is expected to be referring to the current available G$ rewards that can be claimed by user. But for a new/recent deposit, the amount showed seems to high when it should be 0 or close to cero and raising.

**Steps to Reproduce**
1. Assure you have nothing staked.
2. Stake any amount
3. Go to portfolio and check how much G$s you have earned so far by watching the "G$ rewards" column.
4. Is that amount corresponded to the reality?
5. Claim rewards (see issue #81 or just withdraw liquidity and receive rewards) and verify that both numbers are not the same
...

The images below correspond to few moments after a Staking deposit (from zero) was made.

<img width="152" alt="Captura de pantalla 2021-12-16 a las 12 39 05" src="https://user-images.githubusercontent.com/22507864/146365145-f3f86d3b-b9ca-4677-9fd5-906d4e57f413.png">
<img width="285" alt="Captura de pantalla 2021-12-16 a las 12 44 58" src="https://user-images.githubusercontent.com/22507864/146365910-8d003824-58c5-4935-a169-9fefee6511c8.png">
<img width="140" alt="Captura de pantalla 2021-12-16 a las 12 45 11" src="https://user-images.githubusercontent.com/22507864/146365938-1157ebe8-4724-478d-9011-d42e92541868.png">

**Expected Behavior**
G$ Rewards column should disclaim the amount of G$ tokens claimable by user.

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by sepu85** [comment]
<img width="353" alt="Captura de pantalla 2021-12-16 a las 13 54 46" src="https://user-images.githubusercontent.com/22507864/146375866-afec0e7b-f974-4d4d-a306-16099b313f0d.png">

here just an example about how app.fuse.fi has both options

**Comment by sirpy** [comment]
@sepu85 on what network is that? kovan?
if you claim your rewards and thats what you get then it is ok

**Comment by sepu85** [comment]
Yeah, I think I was just confused, let's close this!
