### ISSUE TITLE
(Bug) wiithdraw missing option to withdraw into interest token

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#83]
In portfolio page when withdrawing from Trust Fund the popup should show a toggle to withdraw into interest token
**just like when staking you have the toggle to deposit interest token.**

![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/c37c7edb-729f-4f83-a78f-52ee1c9e744a)

Technical hints
- see SimpleStakingContract.
 - staking.ts line 883, simply false needs to be converted to a variable 
`    else req = contract.methods.withdrawStake(toWithdraw, false).send({ from: account })` 

Definition of Done
- [x]  user should see toggle button to withdraw into interest token
- [x] when user withdraw X% of USDC into interest token he should receive same value of aUSDC tokens
- [x] when user withdraw X% of DAI into interest token he should receive same value of cDAI tokens

**Comment by YpetrovAJ** [comment]
@sirpy check the pr here, it's a draft if everything is okay we'll create the right one

**Comment by artqadev** [comment]
Hi everyone :) 
Verified.

Thank you!

**Comment by sirpy** [comment]
@Devartjoker instead of withdraw into interest token it should say
"Withdraw as ${iToken.symbol}"
meaning it should read the symbol of the interest token (iToken). for example "Withdraw as cDAI" and "Withdraw as aUSDC"
