### ISSUE TITLE
Main page page should be 'swap' instead of 'dashboard'

### ISSUE THREAD

**Issue by galw** [GoodDollar/GoodProtocolUI#85]
**Bug Description**
When you open the main page it should go 'swap' instead of 'dashboard'.
For example, in this deployed version when you go to https://v2.goodswap.xyz/ it should go to https://v2.goodswap.xyz/#/swap instead of https://v2.goodswap.xyz/#/dashboard

**Comment by mukulshakya** [comment]
PR - https://github.com/GoodDollar/GoodProtocolUI/pull/86
