### ISSUE TITLE
add Discord link to support

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#87]
**Is your feature request related to a problem? Please describe.**
We are aiming to bring protocol-UI users to our community in Discord instead of telegram.

**Describe the solution you'd like**
Please add a Discord (logo) button and hyperlink it with the following link: https://discord.gg/RKVHwdQtme
![108-1084991_discord-logo-transparent-background-discord-logo-png-png](https://user-images.githubusercontent.com/22507864/146917324-70bf0203-0d1d-4cb9-9482-9dbdacd26ba5.png)

**Describe alternatives you've considered**
We can both:
- [ ] add a new Discord Button
- [ ] replace current Telegram button with Discord Button

https://discord.gg/RKVHwdQtme

**Additional context**
this is URGENT and LAST MINUTE request, would be super Nice-to-Have before the launch today.

**Comment by mukulshakya** [comment]
PR - https://github.com/GoodDollar/GoodProtocolUI/pull/89
