### ISSUE TITLE
Disclose proper Network name regarding issue #69

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#88]
**Bug Description**
In issue #69 the G$ staking feature over Fuse network was enabled, Although:
1. When in a Non-Fuse network, the button is not disclosing the right variable:
<img width="979" alt="Captura de pantalla 2021-12-21 a las 10 37 46" src="https://user-images.githubusercontent.com/22507864/146907159-833687ce-b2d7-4072-ad10-19d0493bbceb.png">
it says "Switch to {Network}" instead "Switch to Fuse"

**Steps to Reproduce**
1. Go to Staking Section
2. Select any Network except Fuse Network.
3. Have a look at the text in the Governance Staking button.
...

**Expected Behavior**
When the User is in a non Fuse Network, the disclosed button should say "Switch to Fuse"

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by mukulshakya** [comment]
Updated, and should work with language change as well
![image](https://user-images.githubusercontent.com/34328275/147399044-0bbaec76-3fa4-497a-b1b5-e9509a23c68f.png)
![image](https://user-images.githubusercontent.com/34328275/147399052-cbf4ba94-0318-4ab3-9c88-07d79dba1832.png)
