### ISSUE TITLE
(Bug) swap issues

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#90]
- [x] G$ icon missing #92
- [x] liquidity provider fee seems to be fixed on 0.3 ETH, that should be fixed at 0.3% or calculated to 0.3% of the input amount
- [x] GDX - when swapping X->G$ it should show +GDX ie +500 and when G$->X it should show -GDX
since when buying you receive GDX and when selling you spend GDX

![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/f063a8db-f10f-414c-b70e-696494f3d323)

**Comment by mukulshakya** [comment]
Hi @gustavo,

I do not have any token balances in my account to replicate the same can you help me with some test account or any way to test?

**Comment by mukulshakya** [comment]
cc: @adaptivecodeio

**Comment by sirpy** [comment]
@mukulshakya use ropsten/kovan faucet

**Comment by mukulshakya** [comment]
Hi @sirpy what's that? i don't have any idea

**Comment by sepu85** [comment]
hey @sirpy, I find the `Liquidity provider fee`parameter and its explanatory bubble quite missleading. Can we add to the bubble that such a fee is a 3rd party fee AND that if user purchases from cDAI the fee is not applicable?
![Captura de pantalla 2021-12-28 a las 14.57.45.png](https://images.zenhubusercontent.com/5c17881eb59cfb36f158d73a/dc088372-6dee-4c0a-8ea8-690161d8df3b)

also, that fee increases if the route increase, correct?

**Comment by sirpy** [comment]
Yeah sure we can change the text to whatever you want.
no the fee will always be 0.3% regardless of route

Hadar Rottenberg
Technical Lead, GoodDollar
+972-507 319 093  (telegram <http://t.me/sirpy>, whatsapp)  blog
<https://medium.com/dablock>  gooddollar.org <http://www.gooddollar.org/>



* <https://www.facebook.com/TheGoodDollar>
<https://twitter.com/TheGoodDollar>
<http://instagram.com/gooddollarorg>   <http://t.me/GoodDollarX>
<https://www.linkedin.com/company/gooddollar/>
***@***.***>
<http://youtube.com/channel/UC_8oVeHIUo9U8gAc2BwaviA>
<http://reddit.com/user/GoodDollar>   <https://github.com/gooddollar>
  Join the OpenUBI <https://t.me/openUBI> movement!*

**Comment by sepu85** [comment]
cool, I just checked and when purchasing from cDAI, the LP fee is equal to zero, which is ok!!

@mukulshakya @adaptivecodeio the following change needs to be done ASAP as this missinformation is preventing people to purchase the token!
- [ ] Change `0.3 ETH` to `0.3%` 
- [ ] Change buble text to: `Swapping G$ against GoodReserve has no third party fees if you swap from/to cDAI as it's our reserve token. Swapping G$s from/to other assets implies a 0.3% of fee going to 3rd party AMM liquidity providers`

**Comment by mukulshakya** [comment]
Hi @sirpy @sepu85 i am still not sure on how can i get test tokens to replicate the following.

Message i’ll check and update

**Comment by sepu85** [comment]
@mukulshakya @adaptivecodeio sorry but it's difficult to tolerate that such an urgent and no complex bug to be still open all this time because a dev doesn't have test tokens...

![Captura de pantalla 2022-01-04 a las 10.00.45.png](https://images.zenhubusercontent.com/5c17881eb59cfb36f158d73a/04b3d137-bffb-4a5c-a104-baca85a121bf)

https://gitter.im/kovan-testnet/faucet

**Comment by sirpy** [comment]
@mukulshakya @sepu85 that faucet isnt working actually:)
try
https://faucets.chain.link/

**Comment by mukulshakya** [comment]
Hi @sepu85 attaching screenshots for ref

Updated tooltip text 
![image](https://user-images.githubusercontent.com/34328275/148216810-ced70dc8-7ae1-4701-a99a-38fe7ac7953c.png)

Buying G$
![image](https://user-images.githubusercontent.com/34328275/148217142-289b670d-d3ea-4558-a501-47069e1227b3.png)

Selling G$
![image](https://user-images.githubusercontent.com/34328275/148217235-555dc029-6ff9-40f6-b9bc-7715fefa5a13.png)

**Comment by mukulshakya** [comment]
Updated tooltip text 
![image](https://user-images.githubusercontent.com/34328275/148217836-a99d381b-713a-45a0-bbe3-5ee9594c5809.png)

**Comment by womaninblockchain** [comment]
@sirpy @sepu85 - Fixed

**Comment by sepu85** [comment]
awsome! @mukulshakya is this merged already?

**Comment by mukulsib** [comment]
@sepu85 not yet merged, @sirpy please review

**Comment by mukulshakya** [comment]
Not yet @sepu85, waiting for the signoff from @sirpy

**Comment by sepu85** [comment]
@mukulshakya just seeing...

why is there a liquidity provider fee of 1.91328% when swapping from G$ to ETH??

**Comment by sirpy** [comment]
@mukulshakya @womaninblockchain see @sepu85 comment
