### ISSUE TITLE
Wrong Success Message after G$ Staking for GoodDAO governance

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#91]
**Bug Description**
After staking G$s in GoodDAO staking, the disclosed message is the one foreseen for GoodStakes staking, not the GoodDAO staking.
<img width="776" alt="Captura de pantalla 2021-12-21 a las 15 58 16" src="https://user-images.githubusercontent.com/22507864/146960807-6d5940c7-7e0f-42a5-b9cc-d31c85b087a5.png">

The button message is therefore also wrong. Please perform following changes:
- [ ] Change "Did you ... world?" strint to "You have just staked your G$s towards our GoodDAO, this action is gonna reward you with GOOD governance tokens, which are non-transferable so can't be traded."
- [ ] Change "Yes, I did" to "Go to Portfolio" and asure the link address the user towards the portfolio.

**Steps to Reproduce**
1. Connect to Fuse Network
2. Assure you have some G$s available to stake
3. Click on Stake under GoodDAO Stake. Aprove spenditure and finish the process.
4. Wait for the success message. It's referring to a the UBI staking, not the governance one.

...

**Expected Behavior**
Just the right message.

**Additional Context**

**Comment by mukulshakya** [comment]
This is how it looks now 
![image](https://user-images.githubusercontent.com/34328275/147398800-47fb21c7-e973-480a-b063-015835b727c3.png)

**Comment by sirpy** [comment]
@mukulshakya @sepu85 
what about the message for regular staking?

**Comment by mukulshakya** [comment]
@sirpy for all other cases the message will be same as before, and rest maybe @sepu85 can confirm if any more change is expected.

**Comment by sirpy** [comment]
@mukulshakya it shouldnt
both should have the "go to protfolio"/"close"
and @sepu85 should provide the message text

**Comment by mukulshakya** [comment]
Hi @sepu85 Can you please share the 'text' to update 

> @mukulshakya it shouldnt both should have the "go to protfolio"/"close" and @sepu85 should provide the message text

Hi @sepu85 can you please share 'text'to update?

**Comment by sepu85** [comment]
hey @mukulshakya yes, I actually have a change suggestion just on the last phrase of the text:

"You have just staked your G$s, this action is gonna reward you with GOOD governance tokens, which you can use for voting on our GoodDAO."

**Comment by sirpy** [comment]
@sepu85 we need the message text for ubi staking also
