### ISSUE TITLE
(Bug) G$ token icon is missing everywhere

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#92]
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/566910bb-9ccd-4165-9b0a-b5d7e7f06b18)

- [x] fix missing G$ icons in swap
- [x] in stake
- [x] in portfolio
- [x] update the add to metamask icons for G$X, GOOD, G$
- [x] verify it works in all networks fuse/ropsten/kovan/ethereum

**Comment by sepu85** [comment]
G$ Logo:
![G$ Coin](https://user-images.githubusercontent.com/22507864/146965921-2fa59a78-b7f6-4ce2-9163-deedaf625cac.png)

G$X Logo:
![G$X Coin B](https://user-images.githubusercontent.com/22507864/146965956-7425d854-7787-48bf-b586-4e2f0f55c181.png)

GOOD logo:
![GOOD Coin](https://user-images.githubusercontent.com/22507864/146966019-90dcb7dc-ff2e-49be-812f-b82fbcf78db4.png)

**Comment by mukulshakya** [comment]
![image](https://user-images.githubusercontent.com/34328275/147399013-155242d6-0ece-484e-8c8f-63f4dd19aba7.png)
![image](https://user-images.githubusercontent.com/34328275/147399022-d477ac42-d018-4c3c-8c60-dcb39f12c794.png)

**Comment by womaninblockchain** [comment]
@sirpy @sepu85 - fixed

**Comment by sirpy** [comment]
@womaninblockchain @mukulshakya 
this isnt fixed in SWAP when using mainnet (ethereum)
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/86b2cdd5-9f0a-411d-b6cc-147f09a24d62)

**Comment by imanshu03** [comment]
@sirpy The Image URL set for G$ Logo in Mainnet does not exist :- https://raw.githubusercontent.com/trustwallet/assets/tree/master/blockchains/ethereum/assets/0x4738C5e91C4F809da21DD0Df4B5aD5f699878C1c/logo.png

That is why we are not able to see G$ Logo. Please tell me the URL from where we can fetch the G$ logo

**Comment by Devartjoker** [comment]
Icons changed everywhere except for a couple of compound tokens on mainnet, for which I could not find corresponding icons. I was searching on https://tokenlists.org/ in every list possible.

**Comment by sirpy** [comment]
@Devartjoker which tokens?

**Comment by sirpy** [comment]
@Devartjoker 
We dont need these tokens in the Swap.
Where are they loaded from to begin with?

**Comment by artqadev** [comment]
Hi @Devartjoker 

----Dev env----
**General:**
Can't find any icon in portfolio page
**using FUSE:**
GDX token (not only icon) is absent in wallet balance and in import to metamask popup window
**using Ethereum (mainnet):**
in Swap -> Select token -> there is no G$X token's icon

----STG env----
All listed above included
AND
**using Ropsten:**
in Swap -> Swap to -> there is no G$ token's icon
in Swap -> Swap from -> there is no GOOD token's icon

Thank you!
