### ISSUE TITLE
Coinbase browser extension error

### ISSUE THREAD

**Issue by annastone-86** [GoodDollar/GoodProtocolUI#93]
Metamask browser extension doesn't work with Coinbase browser extension. Had to disable Coinbase browser extension in order for Metamask to work on the new UI

**Comment by L03TJ3** [comment]
@annastone-86 Hi, so.. you say it didn't work at all right? what wasn't working exactly for you? As on my end, it does work.... though really wonky... that I admit :)

@devs 
anyone knows why on fi-qa coinbase wallet doesn't pop-up at all? (locally and goodswap act for me the same tho..)

Second:
what is the required solution?
It seems an active issue in web3-react:
https://github.com/NoahZinsmeister/web3-react/issues/300

And also, just 6 days ago closed, so we will have to do a work-around
In the issue thread, one suggests making Coinbase Wallet / Metamask triggered with two separate buttons.
That a viable solution?
