### ISSUE TITLE
portfolio/staking data should be polled and updated

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#94]
Staking/Portfolio doesnt update after a user action
- [ ] staking/portfolio should refresh when user focuses on tab again
- [ ] staking/portfolio should trigger a refresh once user TX is confirmed

**Sushiswap code should probably already have tools and hooks for that**

**Comment by imanshu03** [comment]
@sirpy Please specify the delay in seconds for polling

**Comment by womaninblockchain** [comment]
@sirpy @sepu85 
Fixed - To review

**Comment by sirpy** [comment]
@womaninblockchain i've changed my mind
refresh should happen after user TX or after user comes back to tab

**Comment by womaninblockchain** [comment]
Ok @sirpy .
@imanshu03

**Comment by imanshu03** [comment]
@sirpy Refresh is already happening when user comes to the tab or any TX happens
All the requirements excluding portfolio are already taken care of in our code
If you want I can add a refresh at component unmounting ? If not so then there is no dev required for this ticket

**Comment by imanshu03** [comment]
@sirpy Refresh already happens after user performs a TX. I'll add the logic to refresh when user comes back to the tab
