### ISSUE TITLE
(Bug) social apy and GOOD rewards are not correct on AAVE staking

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#95]
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/3f910d4e-f175-4e13-a4f7-1001a306faaa)

GOOD should not be zero and social apy should be roughly the same as on compound

**Comment by sepu85** [comment]
@adaptivecodeio Social APY is Third party Protocol APY / Reserve Ratio if third party APY (e.g. compound on DAI) is 3% and reserve ratio is 85%, then Social APY is 3 / 0.85 = 3.53% Same for Aave USDC ofc.

Raising this to top priority as it's generating a trust issue, and should also be low effort.
