### ISSUE TITLE
(Bug) dapp webpage doesn't load on Safari 

### ISSUE THREAD

**Issue by annastone-86** [GoodDollar/GoodProtocolUI#96]
The webpage shows as blank, doesn't load up the content of the dapp page

- #97 might be related
- probably related to metamask not extension not available on safari/mobile browsers

**Comment by imanshu03** [comment]
@sirpy @womaninblockchain 
Application is now accessible on Safari.

**Comment by womaninblockchain** [comment]
Is fixed
