### ISSUE TITLE
Blank page on mobile

### ISSUE THREAD

**Issue by annastone-86** [GoodDollar/GoodProtocolUI#97]
Site doesn't load on Chrome on mobile, Screenshot taken from android phone

![photo_2021-12-21 11 32 59](https://user-images.githubusercontent.com/62283025/146965446-31f8b7de-7f8e-4668-bb01-87e0a70ad5e7.jpeg)

**Comment by sepu85** [comment]
@adaptivecodeio is there any other issue dealing with this? Lot of users are reporting their willing/need to connect to the Dapp through metamask.

**Comment by sepu85** [comment]
actually, the problem is not only form from mobile, but from any browser (also PC) that does not have metamask extension installed.

**Comment by imanshu03** [comment]
@wo

**Comment by imanshu03** [comment]
@sirpy  @womaninblockchain 
Application is now accessible on mobile devices.
I have verified for Chrome on Android, Safari on iOS and Chrome on iOS.

**Comment by womaninblockchain** [comment]
@sepu85 Fixed

**Comment by sepu85** [comment]
is this merged already @womaninblockchain ?

**Comment by sirpy** [comment]
@sepu85 if you scroll up a little you would see 
![image](https://user-images.githubusercontent.com/671095/148279977-bfd10af9-e07e-4255-90b5-65672bf3b6c3.png)

that's the PR and you can see that it is still open. once it is merged you see that it is merged

@imanshu03 we asked countless times that you connect the PRs to the issues this way its easier to understand the status of everything

**Comment by imanshu03** [comment]
@sirpy I had connected the PR to the issue just after creating the PR as mentioned by you earlier. You can refer to the time log as well.
