### ISSUE TITLE
(Bug) multiplier tooltip not clear

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#98]
![image.png](https://images.zenhubusercontent.com/5d5081131325bafe066d2c4e/f78a377c-558f-4eeb-a501-de53a4ec1ae7)

what does it mean at this point you can claim more G$?

**Comment by sepu85** [comment]
yep!

here what stated in documentation @sirpy 

<img width="796" alt="Captura de pantalla 2021-12-21 a las 19 16 27" src="https://user-images.githubusercontent.com/22507864/146978920-f5580ca5-e409-4bd0-8063-82145413d5a8.png">

https://gooddollar.gitbook.io/gooddocs/protocol-v2/elements-of-the-gooddollar-ecosystem

**Comment by sepu85** [comment]
@sirpy I'd propose to change the word `claim` in that bubble to `be rewarded with`.

**Comment by artqadev** [comment]
Hi everyone :) 
Verified, e.g.:
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/bf367cee-4392-4457-a4ae-bb935051acc9)

Thank you!

**Comment by artqadev** [comment]
Prod checked
